/* SPDX-License-Identifier: GPL-2.0-only */
#include "target_typed_expression.h"
#include <stdlib.h>
#include <string.h>
#if defined(__clang__)
#pragma clang diagnostic ignored "-Wunused-parameter"
#endif
#define MAX 65536U
static int bad(enum tcti_typed_error *e,enum tcti_typed_error v){if(e)*e=v;return -1;}
static int grow(void **p,size_t *c,size_t n,size_t z){size_t q=*c?*c:32;void *r;while(q<n){if(q>SIZE_MAX/2)return -1;q*=2;}r=realloc(*p,q*z);if(!r)return -1;*p=r;*c=q;return 0;}
int tcti_typed_literal(struct tcti_typed_expression *x,enum tcti_typed_type t,uint8_t w,uint64_t v,enum tcti_typed_type et,uint8_t ew,struct tcti_typed_provenance p,uint32_t *o,enum tcti_typed_error *e){struct tcti_typed_node n={.type=t,.element_type=et,.op=TCTI_TYPED_LITERAL,.width=w,.element_width=ew,.first_child=TCTI_TYPED_NONE,.parent=TCTI_TYPED_NONE,.provenance=p};if(!x||!o||x->node_count==MAX||(t==TCTI_TYPED_BOOL&&w)||(t==TCTI_TYPED_SET&&(ew==0||ew>64))||(t!=TCTI_TYPED_BOOL&&t!=TCTI_TYPED_SET&&(w==0||w>64)))return bad(e,TCTI_TYPED_ARGUMENT);if(grow((void **)&x->nodes,&x->node_capacity,x->node_count+1,sizeof(*x->nodes)))return bad(e,TCTI_TYPED_MEMORY);*o=(uint32_t)x->node_count;x->nodes[x->node_count++]=n;if(e)*e=TCTI_TYPED_OK;return 0;}
int tcti_typed_apply(struct tcti_typed_expression *x,enum tcti_typed_op op,const uint32_t *c,size_t n,struct tcti_typed_provenance p,uint32_t *o,enum tcti_typed_error *e){struct tcti_typed_node q={.op=op,.first_child=(uint32_t)x->child_count,.child_count=(uint32_t)n,.parent=TCTI_TYPED_NONE,.provenance=p};struct tcti_typed_node *a,*b;if(!x||!c||!o||n==0||n>2||x->node_count==MAX)return bad(e,TCTI_TYPED_ARGUMENT);for(size_t i=0;i<n;i++){if(c[i]>=x->node_count)return bad(e,TCTI_TYPED_ARGUMENT);if(x->nodes[c[i]].parent!=TCTI_TYPED_NONE)return bad(e,TCTI_TYPED_OWNED);if(i&&c[i]==c[0])return bad(e,TCTI_TYPED_OWNED);}a=&x->nodes[c[0]];b=n==2?&x->nodes[c[1]]:0;if(a->depth>=TCTI_TYPED_MAX_DEPTH)return bad(e,TCTI_TYPED_LIMIT);q.depth=a->depth+1;if(op==TCTI_TYPED_NOT||op==TCTI_TYPED_UINT||op==TCTI_TYPED_SINT){if(n!=1)return bad(e,TCTI_TYPED_ARITY);if(op==TCTI_TYPED_NOT){if(a->type!=TCTI_TYPED_BOOL)return bad(e,TCTI_TYPED_TYPE);q.type=TCTI_TYPED_BOOL;}else{if(a->type!=TCTI_TYPED_UNSIGNED&&a->type!=TCTI_TYPED_SIGNED)return bad(e,TCTI_TYPED_TYPE);q.type=op==TCTI_TYPED_UINT?TCTI_TYPED_UNSIGNED:TCTI_TYPED_SIGNED;q.width=a->width;}}else{if(n!=2)return bad(e,TCTI_TYPED_ARITY);if(b->depth>=TCTI_TYPED_MAX_DEPTH)return bad(e,TCTI_TYPED_LIMIT);if(b->depth+1>q.depth)q.depth=b->depth+1;if(op==TCTI_TYPED_IN){if(b->type!=TCTI_TYPED_SET||a->type!=b->element_type||a->width!=b->element_width)return bad(e,TCTI_TYPED_TYPE);}else if(op==TCTI_TYPED_AND||op==TCTI_TYPED_OR||op==TCTI_TYPED_IMPLIES||op==TCTI_TYPED_IFF){if(a->type!=TCTI_TYPED_BOOL||b->type!=TCTI_TYPED_BOOL)return bad(e,TCTI_TYPED_TYPE);}else if(a->type!=b->type||a->width!=b->width||(a->type!=TCTI_TYPED_UNSIGNED&&a->type!=TCTI_TYPED_SIGNED))return bad(e,TCTI_TYPED_TYPE);q.type=TCTI_TYPED_BOOL;}if(grow((void **)&x->children,&x->child_capacity,x->child_count+n,sizeof(*x->children))||grow((void **)&x->nodes,&x->node_capacity,x->node_count+1,sizeof(*x->nodes)))return bad(e,TCTI_TYPED_MEMORY);memcpy(x->children+x->child_count,c,n*sizeof(*c));for(size_t i=0;i<n;i++)x->nodes[c[i]].parent=(uint32_t)x->node_count;x->child_count+=n;*o=(uint32_t)x->node_count;x->nodes[x->node_count++]=q;if(e)*e=TCTI_TYPED_OK;return 0;}
void tcti_typed_destroy(struct tcti_typed_expression *x){if(!x)return;free(x->nodes);free(x->children);memset(x,0,sizeof(*x));}
