load(":kernel_uapi.bzl", "orlix_kernel_uapi", "orlix_kernel_uapi_variant")

package(default_visibility = ["//visibility:private"])

exports_files(["kbuild_persist.py"])

orlix_kernel_uapi(
    name = "uapi",
    linux_makefile = "@orlix_linux_source//:Makefile",
    linux_source = "@orlix_linux_source//:source",
    tags = ["manual"],
    visibility = ["//bazel/feasibility:__subpackages__"],
)

[
    orlix_kernel_uapi_variant(
        name = "uapi_%s_%s" % (destination, profile),
        destination = destination,
        profile = profile,
        tags = ["manual"],
        uapi = ":uapi",
        visibility = ["//bazel/feasibility:__subpackages__"],
    )
    for destination in [
        "iphoneos",
        "iphonesimulator",
    ]
    for profile in [
        "development",
        "release",
    ]
]
