/* SPDX-License-Identifier: GPL-2.0-only */
#include "target_feature_applicability_generator.h"

#include <inttypes.h>
#include <stdint.h>
#include <string.h>

#define ORLIX_TCTI_AARCHMRS_INSTRUCTIONS_SHA256 \
	"a1ad2c6538a47cd97d8762791ac5af88bce1d5f6aff096c9b77aef853e76acfe"
#define ORLIX_TCTI_AARCHMRS_FEATURES_SHA256 \
	"633259000ffd3da32900bd0c0c1beae4a9eea7095c278f74d62a00c846b41187"

static int emit_c_string(FILE *output, const char *text)
{
	const unsigned char *cursor = (const unsigned char *)text;

	if (fputc('"', output) == EOF)
		return -1;
	while (*cursor) {
		if (*cursor == '"' || *cursor == '\\') {
			if (fputc('\\', output) == EOF || fputc(*cursor, output) == EOF)
				return -1;
		} else if (*cursor >= 0x20U && *cursor <= 0x7eU) {
			if (fputc(*cursor, output) == EOF)
				return -1;
		} else if (fprintf(output, "\\%03o", (unsigned int)*cursor) < 0) {
			return -1;
		}
		cursor++;
	}
	return fputc('"', output) == EOF ? -1 : 0;
}

static int emit_witness(FILE *output, const signed char *witness, size_t count)
{
	size_t index;

	if (fputc('"', output) == EOF)
		return -1;
	for (index = 0; index < count; index++)
		if (fprintf(output, "\\%03o", (unsigned int)(uint8_t)witness[index]) < 0)
			return -1;
	return fputc('"', output) == EOF ? -1 : 0;
}

static enum orlix_tcti_target_feature_applicability_error validate(
	const struct orlix_tcti_feature_model *model,
	const struct orlix_tcti_target_inventory *inventory,
	const struct orlix_tcti_target_feature_sat_audit *audit)
{
	size_t index;

	if (!model || !inventory || !audit)
		return ORLIX_TCTI_TARGET_FEATURE_APPLICABILITY_INVALID_ARGUMENT;
	if (inventory->leaf_count != ORLIX_TCTI_A64_TARGET_LEAF_COUNT)
		return ORLIX_TCTI_TARGET_FEATURE_APPLICABILITY_PIN_MISMATCH;
	if (audit->leaf_count != inventory->leaf_count ||
	    audit->parameter_count != model->parameter_count || !audit->leaves)
		return ORLIX_TCTI_TARGET_FEATURE_APPLICABILITY_AUDIT_MISMATCH;
	if (model->parameter_count && !audit->witnesses)
		return ORLIX_TCTI_TARGET_FEATURE_APPLICABILITY_WITNESS_UNAVAILABLE;
	for (index = 0; index < inventory->leaf_count; index++) {
		const signed char *witness;
		size_t parameter;

		if (audit->leaves[index] == ORLIX_TCTI_TARGET_FEATURE_SAT_IMPOSSIBLE)
			continue;
		if (audit->leaves[index] != ORLIX_TCTI_TARGET_FEATURE_SAT_APPLICABLE)
			return ORLIX_TCTI_TARGET_FEATURE_APPLICABILITY_AUDIT_MISMATCH;
		if (!model->parameter_count)
			continue;
		witness = orlix_tcti_target_feature_sat_witness(audit, index);
		if (!witness)
			return ORLIX_TCTI_TARGET_FEATURE_APPLICABILITY_WITNESS_UNAVAILABLE;
		for (parameter = 0; parameter < model->parameter_count; parameter++)
			if (witness[parameter] != -1 && witness[parameter] != 1)
				return ORLIX_TCTI_TARGET_FEATURE_APPLICABILITY_WITNESS_INVALID;
	}
	return ORLIX_TCTI_TARGET_FEATURE_APPLICABILITY_OK;
}

static int copy_staged(FILE *stage, FILE *output)
{
	unsigned char buffer[4096];
	size_t count;

	if (fflush(stage) || fseek(stage, 0, SEEK_SET))
		return -1;
	while ((count = fread(buffer, 1, sizeof(buffer), stage)) != 0)
		if (fwrite(buffer, 1, count, output) != count)
			return -1;
	return ferror(stage) || ferror(output) ? -1 : 0;
}

const char *orlix_tcti_target_feature_applicability_error_name(
	enum orlix_tcti_target_feature_applicability_error error)
{
	switch (error) {
	case ORLIX_TCTI_TARGET_FEATURE_APPLICABILITY_OK: return "success";
	case ORLIX_TCTI_TARGET_FEATURE_APPLICABILITY_INVALID_ARGUMENT: return "invalid argument";
	case ORLIX_TCTI_TARGET_FEATURE_APPLICABILITY_PIN_MISMATCH: return "pinned inventory mismatch";
	case ORLIX_TCTI_TARGET_FEATURE_APPLICABILITY_AUDIT_MISMATCH: return "SAT audit mismatch";
	case ORLIX_TCTI_TARGET_FEATURE_APPLICABILITY_WITNESS_UNAVAILABLE: return "SAT witness unavailable";
	case ORLIX_TCTI_TARGET_FEATURE_APPLICABILITY_WITNESS_INVALID: return "SAT witness invalid";
	case ORLIX_TCTI_TARGET_FEATURE_APPLICABILITY_IO: return "I/O failure";
	}
	return "unknown failure";
}

enum orlix_tcti_target_feature_applicability_error
orlix_tcti_target_feature_applicability_emit(const struct orlix_tcti_feature_model *model,
	const struct orlix_tcti_target_inventory *inventory,
	const struct orlix_tcti_target_feature_sat_audit *audit, FILE *output)
{
	enum orlix_tcti_target_feature_applicability_error error;
	FILE *stage;
	size_t index;

	if (!output)
		return ORLIX_TCTI_TARGET_FEATURE_APPLICABILITY_INVALID_ARGUMENT;
	error = validate(model, inventory, audit);
	if (error != ORLIX_TCTI_TARGET_FEATURE_APPLICABILITY_OK)
		return error;
	stage = tmpfile();
	if (!stage)
		return ORLIX_TCTI_TARGET_FEATURE_APPLICABILITY_IO;
	if (fprintf(stage,
		"/* SPDX-License-Identifier: BSD-3-Clause */\n"
		"/* Generated by target_feature_applicability_generator.c. Do not edit. */\n"
		"ORLIX_TCTI_A64_FEATURE_APPLICABILITY_SOURCE(\"vFAPA1-A\", \"2026-06_rel\", \"%s\", \"%s\", %uU, %zuU)\n",
		ORLIX_TCTI_AARCHMRS_INSTRUCTIONS_SHA256, ORLIX_TCTI_AARCHMRS_FEATURES_SHA256,
		ORLIX_TCTI_A64_TARGET_LEAF_COUNT, model->parameter_count) < 0)
		goto io;
	for (index = 0; index < inventory->leaf_count; index++) {
		const struct orlix_tcti_target_leaf *leaf = &inventory->leaves[index];
		const signed char *witness = NULL;
		unsigned int status = audit->leaves[index] ==
			ORLIX_TCTI_TARGET_FEATURE_SAT_APPLICABLE ? 1U : 0U;

		if (status && model->parameter_count)
			witness = orlix_tcti_target_feature_sat_witness(audit, index);
		if (fprintf(stage, "ORLIX_TCTI_A64_FEATURE_APPLICABILITY_ROW(%zuU, ", index) < 0 ||
		    emit_c_string(stage, leaf->name ? leaf->name : "") ||
		    fputs(", ", stage) == EOF ||
		    emit_c_string(stage, leaf->mnemonic ? leaf->mnemonic : "") ||
		    fputs(", ", stage) == EOF ||
		    emit_c_string(stage, leaf->operation_id ? leaf->operation_id : "") ||
		    fprintf(stage, ", %" PRIu32 "U, %uU, ", leaf->condition, status) < 0 ||
		    emit_witness(stage, witness, status ? model->parameter_count : 0U) ||
		    fprintf(stage, ", %zuU)\n", status ? model->parameter_count : 0U) < 0)
			goto io;
	}
	if (copy_staged(stage, output))
		goto io;
	fclose(stage);
	return ORLIX_TCTI_TARGET_FEATURE_APPLICABILITY_OK;
io:
	fclose(stage);
	return ORLIX_TCTI_TARGET_FEATURE_APPLICABILITY_IO;
}
