load(":rootfs.bzl", "orlix_rootfs", "orlix_rootfs_payload")

package(default_visibility = ["//visibility:private"])

orlix_rootfs(
    name = "rootfs",
    gen_init_cpio = "@orlix_linux_source//:usr/gen_init_cpio.c",
    packages = [
        "//bazel/feasibility/packages:coreutils",
        "//bazel/feasibility/packages:bash",
        "//bazel/feasibility/packages:grep",
        "//bazel/feasibility/packages:findutils",
        "//bazel/feasibility/packages:e2fsprogs",
        "//bazel/feasibility/packages:getconf",
        "//bazel/feasibility/packages:getent",
        "//bazel/feasibility/packages:init",
        "//bazel/feasibility/packages:jq",
        "//bazel/feasibility/packages:curl",
        "//bazel/feasibility/packages:zsh",
    ],
    sysroot = "//bazel/feasibility/mlibc:sysroot",
    tags = ["manual"],
    visibility = [
        "//Orlix:__pkg__",
        "//bazel/feasibility:__subpackages__",
        "//bazel/product:__pkg__",
    ],
)

orlix_rootfs_payload(
    name = "payload",
    rootfs = select({
        "//bazel/config:component_promoted": "//bazel/promotion:promoted_rootfs",
        "//conditions:default": ":rootfs",
    }),
    tags = ["manual"],
    visibility = [
        "//Orlix:__pkg__",
        "//bazel/feasibility:__subpackages__",
        "//bazel/product:__pkg__",
    ],
)
