load(":rootfs.bzl", "orlix_rootfs")

package(default_visibility = ["//visibility:private"])

orlix_rootfs(
    name = "rootfs",
    gen_init_cpio = "@orlix_linux_source//:usr/gen_init_cpio.c",
    packages = [
        "//bazel/feasibility/packages:coreutils",
        "//bazel/feasibility/packages:bash",
        "//bazel/feasibility/packages:grep",
        "//bazel/feasibility/packages:findutils",
        "//bazel/feasibility/packages:e2fsprogs",
        "//bazel/feasibility/packages:getconf",
        "//bazel/feasibility/packages:getent",
        "//bazel/feasibility/packages:init",
        "//bazel/feasibility/packages:jq",
        "//bazel/feasibility/packages:curl",
        "//bazel/feasibility/packages:zsh",
    ],
    sysroot = "//bazel/feasibility/mlibc:sysroot",
    tags = ["manual"],
    visibility = ["//bazel/feasibility:__subpackages__"],
)
