// SPDX-License-Identifier: GPL-2.0-only
/*
 * Pinned AARCHMRS 2026-06 direct leaves 2353 through 2504 are the complete
 * classic AdvSIMD structure load/store interval.  It contains LD1-4/ST1-4
 * multiple structures, lane structures, LD1R-4R replication, and immediate
 * and register post-index forms.  The authoritative checked C artifact is
 * consumed directly so no hand-maintained opcode subset can hide a leaf.
 */
#include <kunit/test.h>
#include <linux/bitfield.h>
#include <linux/err.h>
#include <linux/mm.h>
#include <linux/mman.h>
#include <linux/sched.h>
#include <linux/sched/mm.h>
#include <linux/string.h>
#include <linux/syscalls.h>
#include <asm/hosted_exec.h>
#include <asm/processor.h>
#include <asm/ptrace.h>
#include <asm/orlix_tcti.h>

#include "target_instruction_artifact.h"
#include "../decode_aarch64.h"

#define ORLIX_TCTI_ADVSIMD_STRUCTURE_FIRST_SOURCE 2353U
#define ORLIX_TCTI_ADVSIMD_STRUCTURE_LAST_SOURCE  2504U
#define ORLIX_TCTI_ADVSIMD_STRUCTURE_SOURCE_COUNT \
	(ORLIX_TCTI_ADVSIMD_STRUCTURE_LAST_SOURCE - \
	 ORLIX_TCTI_ADVSIMD_STRUCTURE_FIRST_SOURCE + 1U)
#define ORLIX_TCTI_ADVSIMD_STRUCTURE_SVC 0xd4000001U

struct orlix_tcti_advsimd_structure_context {
	u64 simd[ARRAY_SIZE(current->thread.user_simd)];
	unsigned long simd_valid;
	unsigned long fpcr;
	unsigned long fpsr;
};

static int orlix_tcti_advsimd_structure_test_init(struct kunit *test)
{
	struct orlix_tcti_advsimd_structure_context *context;

	context = kunit_kzalloc(test, sizeof(*context), GFP_KERNEL);
	if (!context)
		return -ENOMEM;
	memcpy(context->simd, current->thread.user_simd, sizeof(context->simd));
	context->simd_valid = current->thread.user_simd_valid;
	context->fpcr = current->thread.user_fpcr;
	context->fpsr = current->thread.user_fpsr;
	test->priv = context;
	return 0;
}

static void orlix_tcti_advsimd_structure_test_exit(struct kunit *test)
{
	struct orlix_tcti_advsimd_structure_context *context = test->priv;

	memcpy(current->thread.user_simd, context->simd, sizeof(context->simd));
	current->thread.user_simd_valid = context->simd_valid;
	current->thread.user_fpcr = context->fpcr;
	current->thread.user_fpsr = context->fpsr;
}

static const char *orlix_tcti_advsimd_structure_artifact_string(
	const struct orlix_tcti_target_instruction_artifact *artifact, u32 offset)
{
	if (offset >= artifact->string_pool_size)
		return NULL;
	return (const char *)artifact->string_pool + offset;
}

/*
 * This is an independent pinned contract for every direct AARCHMRS leaf in
 * the classic AdvSIMD structure interval.  It intentionally does not include
 * the source manifest: manifest drift and decoder drift must fail separately.
 */
enum orlix_tcti_advsimd_structure_lane_shape {
	ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE_NONE,
	ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE,
	ORLIX_TCTI_ADVSIMD_STRUCTURE_REPLICATE,
};

struct orlix_tcti_advsimd_structure_contract {
	u32 ordinal;
	const char *leaf_id;
	const char *mnemonic;
	const char *operation_id;
	u32 mask;
	u32 pattern;
	enum orlix_tcti_decode_class decode_class;
	bool load;
	u8 structure_count;
	u8 access_size;
	u8 q0_semantic_width;
	u8 q1_semantic_width;
	enum orlix_tcti_memory_index_mode index_mode;
	enum orlix_tcti_advsimd_structure_lane_shape lane_shape;
	bool interleaved;
};

/*
 * STL1 (ordinal 2403) and LDAP1 (ordinal 2422) are exercised here only for
 * their ordinary structure-transfer state changes.  Their release/acquire
 * ordering guarantees require a separate concurrency proof and are not
 * established by this suite.
 */
#define ORLIX_TCTI_ADVSIMD_STRUCTURE_CONTRACT_ROWS(X) \
	X(2353U, "ST4_asisdlse_R4", "ST4", "ST4_advsimd_mult", 0xbffff000U, 0x0c000000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_MULTIPLE_STRUCTURE, false, 4U, 1U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_SIGNED_OFFSET, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE_NONE, true) \
	X(2354U, "ST1_asisdlse_R4_4v", "ST1", "ST1_advsimd_mult", 0xbffff000U, 0x0c002000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_MULTIPLE_STRUCTURE, false, 4U, 1U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_SIGNED_OFFSET, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE_NONE, false) \
	X(2355U, "ST3_asisdlse_R3", "ST3", "ST3_advsimd_mult", 0xbffff000U, 0x0c004000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_MULTIPLE_STRUCTURE, false, 3U, 1U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_SIGNED_OFFSET, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE_NONE, true) \
	X(2356U, "ST1_asisdlse_R3_3v", "ST1", "ST1_advsimd_mult", 0xbffff000U, 0x0c006000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_MULTIPLE_STRUCTURE, false, 3U, 1U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_SIGNED_OFFSET, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE_NONE, false) \
	X(2357U, "ST1_asisdlse_R1_1v", "ST1", "ST1_advsimd_mult", 0xbffff000U, 0x0c007000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_MULTIPLE_STRUCTURE, false, 1U, 1U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_SIGNED_OFFSET, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE_NONE, false) \
	X(2358U, "ST2_asisdlse_R2", "ST2", "ST2_advsimd_mult", 0xbffff000U, 0x0c008000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_MULTIPLE_STRUCTURE, false, 2U, 1U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_SIGNED_OFFSET, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE_NONE, true) \
	X(2359U, "ST1_asisdlse_R2_2v", "ST1", "ST1_advsimd_mult", 0xbffff000U, 0x0c00a000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_MULTIPLE_STRUCTURE, false, 2U, 1U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_SIGNED_OFFSET, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE_NONE, false) \
	X(2360U, "LD4_asisdlse_R4", "LD4", "LD4_advsimd_mult", 0xbffff000U, 0x0c400000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_MULTIPLE_STRUCTURE, true, 4U, 1U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_SIGNED_OFFSET, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE_NONE, true) \
	X(2361U, "LD1_asisdlse_R4_4v", "LD1", "LD1_advsimd_mult", 0xbffff000U, 0x0c402000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_MULTIPLE_STRUCTURE, true, 4U, 1U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_SIGNED_OFFSET, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE_NONE, false) \
	X(2362U, "LD3_asisdlse_R3", "LD3", "LD3_advsimd_mult", 0xbffff000U, 0x0c404000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_MULTIPLE_STRUCTURE, true, 3U, 1U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_SIGNED_OFFSET, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE_NONE, true) \
	X(2363U, "LD1_asisdlse_R3_3v", "LD1", "LD1_advsimd_mult", 0xbffff000U, 0x0c406000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_MULTIPLE_STRUCTURE, true, 3U, 1U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_SIGNED_OFFSET, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE_NONE, false) \
	X(2364U, "LD1_asisdlse_R1_1v", "LD1", "LD1_advsimd_mult", 0xbffff000U, 0x0c407000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_MULTIPLE_STRUCTURE, true, 1U, 1U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_SIGNED_OFFSET, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE_NONE, false) \
	X(2365U, "LD2_asisdlse_R2", "LD2", "LD2_advsimd_mult", 0xbffff000U, 0x0c408000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_MULTIPLE_STRUCTURE, true, 2U, 1U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_SIGNED_OFFSET, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE_NONE, true) \
	X(2366U, "LD1_asisdlse_R2_2v", "LD1", "LD1_advsimd_mult", 0xbffff000U, 0x0c40a000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_MULTIPLE_STRUCTURE, true, 2U, 1U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_SIGNED_OFFSET, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE_NONE, false) \
	X(2367U, "ST4_asisdlsep_R4_r", "ST4", "ST4_advsimd_mult", 0xbfe0f000U, 0x0c800000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_MULTIPLE_STRUCTURE, false, 4U, 1U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE_NONE, true) \
 X(2368U, "ST1_asisdlsep_R4_r4", "ST1", "ST1_advsimd_mult", 0xbfe0f000U, 0x0c802000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_MULTIPLE_STRUCTURE, false, 4U, 1U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE_NONE, false) \
	X(2369U, "ST3_asisdlsep_R3_r", "ST3", "ST3_advsimd_mult", 0xbfe0f000U, 0x0c804000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_MULTIPLE_STRUCTURE, false, 3U, 1U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE_NONE, true) \
 X(2370U, "ST1_asisdlsep_R3_r3", "ST1", "ST1_advsimd_mult", 0xbfe0f000U, 0x0c806000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_MULTIPLE_STRUCTURE, false, 3U, 1U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE_NONE, false) \
	X(2371U, "ST1_asisdlsep_R1_r1", "ST1", "ST1_advsimd_mult", 0xbfe0f000U, 0x0c807000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_MULTIPLE_STRUCTURE, false, 1U, 1U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE_NONE, false) \
	X(2372U, "ST2_asisdlsep_R2_r", "ST2", "ST2_advsimd_mult", 0xbfe0f000U, 0x0c808000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_MULTIPLE_STRUCTURE, false, 2U, 1U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE_NONE, true) \
 X(2373U, "ST1_asisdlsep_R2_r2", "ST1", "ST1_advsimd_mult", 0xbfe0f000U, 0x0c80a000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_MULTIPLE_STRUCTURE, false, 2U, 1U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE_NONE, false) \
	X(2374U, "ST4_asisdlsep_I4_i", "ST4", "ST4_advsimd_mult", 0xbffff000U, 0x0c9f0000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_MULTIPLE_STRUCTURE, false, 4U, 1U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE_NONE, true) \
 X(2375U, "ST1_asisdlsep_I4_i4", "ST1", "ST1_advsimd_mult", 0xbffff000U, 0x0c9f2000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_MULTIPLE_STRUCTURE, false, 4U, 1U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE_NONE, false) \
	X(2376U, "ST3_asisdlsep_I3_i", "ST3", "ST3_advsimd_mult", 0xbffff000U, 0x0c9f4000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_MULTIPLE_STRUCTURE, false, 3U, 1U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE_NONE, true) \
 X(2377U, "ST1_asisdlsep_I3_i3", "ST1", "ST1_advsimd_mult", 0xbffff000U, 0x0c9f6000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_MULTIPLE_STRUCTURE, false, 3U, 1U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE_NONE, false) \
	X(2378U, "ST1_asisdlsep_I1_i1", "ST1", "ST1_advsimd_mult", 0xbffff000U, 0x0c9f7000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_MULTIPLE_STRUCTURE, false, 1U, 1U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE_NONE, false) \
	X(2379U, "ST2_asisdlsep_I2_i", "ST2", "ST2_advsimd_mult", 0xbffff000U, 0x0c9f8000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_MULTIPLE_STRUCTURE, false, 2U, 1U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE_NONE, true) \
 X(2380U, "ST1_asisdlsep_I2_i2", "ST1", "ST1_advsimd_mult", 0xbffff000U, 0x0c9fa000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_MULTIPLE_STRUCTURE, false, 2U, 1U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE_NONE, false) \
	X(2381U, "LD4_asisdlsep_R4_r", "LD4", "LD4_advsimd_mult", 0xbfe0f000U, 0x0cc00000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_MULTIPLE_STRUCTURE, true, 4U, 1U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE_NONE, true) \
 X(2382U, "LD1_asisdlsep_R4_r4", "LD1", "LD1_advsimd_mult", 0xbfe0f000U, 0x0cc02000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_MULTIPLE_STRUCTURE, true, 4U, 1U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE_NONE, false) \
	X(2383U, "LD3_asisdlsep_R3_r", "LD3", "LD3_advsimd_mult", 0xbfe0f000U, 0x0cc04000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_MULTIPLE_STRUCTURE, true, 3U, 1U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE_NONE, true) \
 X(2384U, "LD1_asisdlsep_R3_r3", "LD1", "LD1_advsimd_mult", 0xbfe0f000U, 0x0cc06000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_MULTIPLE_STRUCTURE, true, 3U, 1U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE_NONE, false) \
	X(2385U, "LD1_asisdlsep_R1_r1", "LD1", "LD1_advsimd_mult", 0xbfe0f000U, 0x0cc07000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_MULTIPLE_STRUCTURE, true, 1U, 1U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE_NONE, false) \
	X(2386U, "LD2_asisdlsep_R2_r", "LD2", "LD2_advsimd_mult", 0xbfe0f000U, 0x0cc08000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_MULTIPLE_STRUCTURE, true, 2U, 1U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE_NONE, true) \
 X(2387U, "LD1_asisdlsep_R2_r2", "LD1", "LD1_advsimd_mult", 0xbfe0f000U, 0x0cc0a000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_MULTIPLE_STRUCTURE, true, 2U, 1U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE_NONE, false) \
	X(2388U, "LD4_asisdlsep_I4_i", "LD4", "LD4_advsimd_mult", 0xbffff000U, 0x0cdf0000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_MULTIPLE_STRUCTURE, true, 4U, 1U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE_NONE, true) \
 X(2389U, "LD1_asisdlsep_I4_i4", "LD1", "LD1_advsimd_mult", 0xbffff000U, 0x0cdf2000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_MULTIPLE_STRUCTURE, true, 4U, 1U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE_NONE, false) \
	X(2390U, "LD3_asisdlsep_I3_i", "LD3", "LD3_advsimd_mult", 0xbffff000U, 0x0cdf4000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_MULTIPLE_STRUCTURE, true, 3U, 1U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE_NONE, true) \
 X(2391U, "LD1_asisdlsep_I3_i3", "LD1", "LD1_advsimd_mult", 0xbffff000U, 0x0cdf6000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_MULTIPLE_STRUCTURE, true, 3U, 1U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE_NONE, false) \
	X(2392U, "LD1_asisdlsep_I1_i1", "LD1", "LD1_advsimd_mult", 0xbffff000U, 0x0cdf7000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_MULTIPLE_STRUCTURE, true, 1U, 1U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE_NONE, false) \
	X(2393U, "LD2_asisdlsep_I2_i", "LD2", "LD2_advsimd_mult", 0xbffff000U, 0x0cdf8000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_MULTIPLE_STRUCTURE, true, 2U, 1U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE_NONE, true) \
 X(2394U, "LD1_asisdlsep_I2_i2", "LD1", "LD1_advsimd_mult", 0xbffff000U, 0x0cdfa000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_MULTIPLE_STRUCTURE, true, 2U, 1U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE_NONE, false) \
	X(2395U, "ST1_asisdlso_B1_1b", "ST1", "ST1_advsimd_sngl", 0xbfffe000U, 0x0d000000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, false, 1U, 1U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_SIGNED_OFFSET, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2396U, "ST3_asisdlso_B3_3b", "ST3", "ST3_advsimd_sngl", 0xbfffe000U, 0x0d002000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, false, 3U, 1U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_SIGNED_OFFSET, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2397U, "ST1_asisdlso_H1_1h", "ST1", "ST1_advsimd_sngl", 0xbfffe400U, 0x0d004000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, false, 1U, 2U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_SIGNED_OFFSET, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2398U, "ST3_asisdlso_H3_3h", "ST3", "ST3_advsimd_sngl", 0xbfffe400U, 0x0d006000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, false, 3U, 2U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_SIGNED_OFFSET, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2399U, "ST1_asisdlso_S1_1s", "ST1", "ST1_advsimd_sngl", 0xbfffec00U, 0x0d008000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, false, 1U, 4U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_SIGNED_OFFSET, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2400U, "ST1_asisdlso_D1_1d", "ST1", "ST1_advsimd_sngl", 0xbffffc00U, 0x0d008400U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, false, 1U, 8U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_SIGNED_OFFSET, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2401U, "ST3_asisdlso_S3_3s", "ST3", "ST3_advsimd_sngl", 0xbfffec00U, 0x0d00a000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, false, 3U, 4U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_SIGNED_OFFSET, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2402U, "ST3_asisdlso_D3_3d", "ST3", "ST3_advsimd_sngl", 0xbffffc00U, 0x0d00a400U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, false, 3U, 8U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_SIGNED_OFFSET, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2403U, "STL1_asisdlso_D1", "STL1", "STL1_advsimd_sngl", 0xbffffc00U, 0x0d018400U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, false, 1U, 8U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_SIGNED_OFFSET, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2404U, "ST2_asisdlso_B2_2b", "ST2", "ST2_advsimd_sngl", 0xbfffe000U, 0x0d200000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, false, 2U, 1U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_SIGNED_OFFSET, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2405U, "ST4_asisdlso_B4_4b", "ST4", "ST4_advsimd_sngl", 0xbfffe000U, 0x0d202000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, false, 4U, 1U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_SIGNED_OFFSET, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2406U, "ST2_asisdlso_H2_2h", "ST2", "ST2_advsimd_sngl", 0xbfffe400U, 0x0d204000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, false, 2U, 2U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_SIGNED_OFFSET, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2407U, "ST4_asisdlso_H4_4h", "ST4", "ST4_advsimd_sngl", 0xbfffe400U, 0x0d206000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, false, 4U, 2U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_SIGNED_OFFSET, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2408U, "ST2_asisdlso_S2_2s", "ST2", "ST2_advsimd_sngl", 0xbfffec00U, 0x0d208000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, false, 2U, 4U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_SIGNED_OFFSET, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2409U, "ST2_asisdlso_D2_2d", "ST2", "ST2_advsimd_sngl", 0xbffffc00U, 0x0d208400U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, false, 2U, 8U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_SIGNED_OFFSET, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2410U, "ST4_asisdlso_S4_4s", "ST4", "ST4_advsimd_sngl", 0xbfffec00U, 0x0d20a000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, false, 4U, 4U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_SIGNED_OFFSET, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2411U, "ST4_asisdlso_D4_4d", "ST4", "ST4_advsimd_sngl", 0xbffffc00U, 0x0d20a400U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, false, 4U, 8U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_SIGNED_OFFSET, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2412U, "LD1_asisdlso_B1_1b", "LD1", "LD1_advsimd_sngl", 0xbfffe000U, 0x0d400000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, true, 1U, 1U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_SIGNED_OFFSET, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2413U, "LD3_asisdlso_B3_3b", "LD3", "LD3_advsimd_sngl", 0xbfffe000U, 0x0d402000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, true, 3U, 1U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_SIGNED_OFFSET, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2414U, "LD1_asisdlso_H1_1h", "LD1", "LD1_advsimd_sngl", 0xbfffe400U, 0x0d404000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, true, 1U, 2U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_SIGNED_OFFSET, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2415U, "LD3_asisdlso_H3_3h", "LD3", "LD3_advsimd_sngl", 0xbfffe400U, 0x0d406000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, true, 3U, 2U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_SIGNED_OFFSET, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2416U, "LD1_asisdlso_S1_1s", "LD1", "LD1_advsimd_sngl", 0xbfffec00U, 0x0d408000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, true, 1U, 4U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_SIGNED_OFFSET, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2417U, "LD1_asisdlso_D1_1d", "LD1", "LD1_advsimd_sngl", 0xbffffc00U, 0x0d408400U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, true, 1U, 8U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_SIGNED_OFFSET, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2418U, "LD3_asisdlso_S3_3s", "LD3", "LD3_advsimd_sngl", 0xbfffec00U, 0x0d40a000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, true, 3U, 4U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_SIGNED_OFFSET, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2419U, "LD3_asisdlso_D3_3d", "LD3", "LD3_advsimd_sngl", 0xbffffc00U, 0x0d40a400U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, true, 3U, 8U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_SIGNED_OFFSET, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2420U, "LD1R_asisdlso_R1", "LD1R", "LD1R_advsimd", 0xbffff000U, 0x0d40c000U, ORLIX_TCTI_DECODE_SIMD_LOAD_REPLICATE, true, 1U, 1U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_SIGNED_OFFSET, ORLIX_TCTI_ADVSIMD_STRUCTURE_REPLICATE, false) \
	X(2421U, "LD3R_asisdlso_R3", "LD3R", "LD3R_advsimd", 0xbffff000U, 0x0d40e000U, ORLIX_TCTI_DECODE_SIMD_LOAD_REPLICATE, true, 3U, 1U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_SIGNED_OFFSET, ORLIX_TCTI_ADVSIMD_STRUCTURE_REPLICATE, false) \
	X(2422U, "LDAP1_asisdlso_D1", "LDAP1", "LDAP1_advsimd_sngl", 0xbffffc00U, 0x0d418400U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, true, 1U, 8U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_SIGNED_OFFSET, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2423U, "LD2_asisdlso_B2_2b", "LD2", "LD2_advsimd_sngl", 0xbfffe000U, 0x0d600000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, true, 2U, 1U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_SIGNED_OFFSET, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2424U, "LD4_asisdlso_B4_4b", "LD4", "LD4_advsimd_sngl", 0xbfffe000U, 0x0d602000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, true, 4U, 1U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_SIGNED_OFFSET, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2425U, "LD2_asisdlso_H2_2h", "LD2", "LD2_advsimd_sngl", 0xbfffe400U, 0x0d604000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, true, 2U, 2U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_SIGNED_OFFSET, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2426U, "LD4_asisdlso_H4_4h", "LD4", "LD4_advsimd_sngl", 0xbfffe400U, 0x0d606000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, true, 4U, 2U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_SIGNED_OFFSET, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2427U, "LD2_asisdlso_S2_2s", "LD2", "LD2_advsimd_sngl", 0xbfffec00U, 0x0d608000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, true, 2U, 4U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_SIGNED_OFFSET, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2428U, "LD2_asisdlso_D2_2d", "LD2", "LD2_advsimd_sngl", 0xbffffc00U, 0x0d608400U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, true, 2U, 8U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_SIGNED_OFFSET, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2429U, "LD4_asisdlso_S4_4s", "LD4", "LD4_advsimd_sngl", 0xbfffec00U, 0x0d60a000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, true, 4U, 4U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_SIGNED_OFFSET, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2430U, "LD4_asisdlso_D4_4d", "LD4", "LD4_advsimd_sngl", 0xbffffc00U, 0x0d60a400U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, true, 4U, 8U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_SIGNED_OFFSET, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2431U, "LD2R_asisdlso_R2", "LD2R", "LD2R_advsimd", 0xbffff000U, 0x0d60c000U, ORLIX_TCTI_DECODE_SIMD_LOAD_REPLICATE, true, 2U, 1U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_SIGNED_OFFSET, ORLIX_TCTI_ADVSIMD_STRUCTURE_REPLICATE, false) \
	X(2432U, "LD4R_asisdlso_R4", "LD4R", "LD4R_advsimd", 0xbffff000U, 0x0d60e000U, ORLIX_TCTI_DECODE_SIMD_LOAD_REPLICATE, true, 4U, 1U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_SIGNED_OFFSET, ORLIX_TCTI_ADVSIMD_STRUCTURE_REPLICATE, false) \
	X(2433U, "ST1_asisdlsop_BX1_r1b", "ST1", "ST1_advsimd_sngl", 0xbfe0e000U, 0x0d800000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, false, 1U, 1U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2434U, "ST3_asisdlsop_BX3_r3b", "ST3", "ST3_advsimd_sngl", 0xbfe0e000U, 0x0d802000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, false, 3U, 1U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2435U, "ST1_asisdlsop_HX1_r1h", "ST1", "ST1_advsimd_sngl", 0xbfe0e400U, 0x0d804000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, false, 1U, 2U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2436U, "ST3_asisdlsop_HX3_r3h", "ST3", "ST3_advsimd_sngl", 0xbfe0e400U, 0x0d806000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, false, 3U, 2U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2437U, "ST1_asisdlsop_SX1_r1s", "ST1", "ST1_advsimd_sngl", 0xbfe0ec00U, 0x0d808000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, false, 1U, 4U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2438U, "ST1_asisdlsop_DX1_r1d", "ST1", "ST1_advsimd_sngl", 0xbfe0fc00U, 0x0d808400U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, false, 1U, 8U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2439U, "ST3_asisdlsop_SX3_r3s", "ST3", "ST3_advsimd_sngl", 0xbfe0ec00U, 0x0d80a000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, false, 3U, 4U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2440U, "ST3_asisdlsop_DX3_r3d", "ST3", "ST3_advsimd_sngl", 0xbfe0fc00U, 0x0d80a400U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, false, 3U, 8U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2441U, "ST1_asisdlsop_B1_i1b", "ST1", "ST1_advsimd_sngl", 0xbfffe000U, 0x0d9f0000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, false, 1U, 1U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2442U, "ST3_asisdlsop_B3_i3b", "ST3", "ST3_advsimd_sngl", 0xbfffe000U, 0x0d9f2000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, false, 3U, 1U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2443U, "ST1_asisdlsop_H1_i1h", "ST1", "ST1_advsimd_sngl", 0xbfffe400U, 0x0d9f4000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, false, 1U, 2U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2444U, "ST3_asisdlsop_H3_i3h", "ST3", "ST3_advsimd_sngl", 0xbfffe400U, 0x0d9f6000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, false, 3U, 2U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2445U, "ST1_asisdlsop_S1_i1s", "ST1", "ST1_advsimd_sngl", 0xbfffec00U, 0x0d9f8000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, false, 1U, 4U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2446U, "ST1_asisdlsop_D1_i1d", "ST1", "ST1_advsimd_sngl", 0xbffffc00U, 0x0d9f8400U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, false, 1U, 8U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2447U, "ST3_asisdlsop_S3_i3s", "ST3", "ST3_advsimd_sngl", 0xbfffec00U, 0x0d9fa000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, false, 3U, 4U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2448U, "ST3_asisdlsop_D3_i3d", "ST3", "ST3_advsimd_sngl", 0xbffffc00U, 0x0d9fa400U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, false, 3U, 8U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2449U, "ST2_asisdlsop_BX2_r2b", "ST2", "ST2_advsimd_sngl", 0xbfe0e000U, 0x0da00000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, false, 2U, 1U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2450U, "ST4_asisdlsop_BX4_r4b", "ST4", "ST4_advsimd_sngl", 0xbfe0e000U, 0x0da02000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, false, 4U, 1U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2451U, "ST2_asisdlsop_HX2_r2h", "ST2", "ST2_advsimd_sngl", 0xbfe0e400U, 0x0da04000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, false, 2U, 2U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2452U, "ST4_asisdlsop_HX4_r4h", "ST4", "ST4_advsimd_sngl", 0xbfe0e400U, 0x0da06000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, false, 4U, 2U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2453U, "ST2_asisdlsop_SX2_r2s", "ST2", "ST2_advsimd_sngl", 0xbfe0ec00U, 0x0da08000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, false, 2U, 4U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2454U, "ST2_asisdlsop_DX2_r2d", "ST2", "ST2_advsimd_sngl", 0xbfe0fc00U, 0x0da08400U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, false, 2U, 8U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2455U, "ST4_asisdlsop_SX4_r4s", "ST4", "ST4_advsimd_sngl", 0xbfe0ec00U, 0x0da0a000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, false, 4U, 4U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2456U, "ST4_asisdlsop_DX4_r4d", "ST4", "ST4_advsimd_sngl", 0xbfe0fc00U, 0x0da0a400U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, false, 4U, 8U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2457U, "ST2_asisdlsop_B2_i2b", "ST2", "ST2_advsimd_sngl", 0xbfffe000U, 0x0dbf0000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, false, 2U, 1U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2458U, "ST4_asisdlsop_B4_i4b", "ST4", "ST4_advsimd_sngl", 0xbfffe000U, 0x0dbf2000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, false, 4U, 1U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2459U, "ST2_asisdlsop_H2_i2h", "ST2", "ST2_advsimd_sngl", 0xbfffe400U, 0x0dbf4000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, false, 2U, 2U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2460U, "ST4_asisdlsop_H4_i4h", "ST4", "ST4_advsimd_sngl", 0xbfffe400U, 0x0dbf6000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, false, 4U, 2U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2461U, "ST2_asisdlsop_S2_i2s", "ST2", "ST2_advsimd_sngl", 0xbfffec00U, 0x0dbf8000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, false, 2U, 4U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2462U, "ST2_asisdlsop_D2_i2d", "ST2", "ST2_advsimd_sngl", 0xbffffc00U, 0x0dbf8400U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, false, 2U, 8U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2463U, "ST4_asisdlsop_S4_i4s", "ST4", "ST4_advsimd_sngl", 0xbfffec00U, 0x0dbfa000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, false, 4U, 4U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2464U, "ST4_asisdlsop_D4_i4d", "ST4", "ST4_advsimd_sngl", 0xbffffc00U, 0x0dbfa400U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, false, 4U, 8U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2465U, "LD1_asisdlsop_BX1_r1b", "LD1", "LD1_advsimd_sngl", 0xbfe0e000U, 0x0dc00000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, true, 1U, 1U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2466U, "LD3_asisdlsop_BX3_r3b", "LD3", "LD3_advsimd_sngl", 0xbfe0e000U, 0x0dc02000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, true, 3U, 1U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2467U, "LD1_asisdlsop_HX1_r1h", "LD1", "LD1_advsimd_sngl", 0xbfe0e400U, 0x0dc04000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, true, 1U, 2U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2468U, "LD3_asisdlsop_HX3_r3h", "LD3", "LD3_advsimd_sngl", 0xbfe0e400U, 0x0dc06000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, true, 3U, 2U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2469U, "LD1_asisdlsop_SX1_r1s", "LD1", "LD1_advsimd_sngl", 0xbfe0ec00U, 0x0dc08000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, true, 1U, 4U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2470U, "LD1_asisdlsop_DX1_r1d", "LD1", "LD1_advsimd_sngl", 0xbfe0fc00U, 0x0dc08400U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, true, 1U, 8U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2471U, "LD3_asisdlsop_SX3_r3s", "LD3", "LD3_advsimd_sngl", 0xbfe0ec00U, 0x0dc0a000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, true, 3U, 4U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2472U, "LD3_asisdlsop_DX3_r3d", "LD3", "LD3_advsimd_sngl", 0xbfe0fc00U, 0x0dc0a400U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, true, 3U, 8U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2473U, "LD1R_asisdlsop_RX1_r", "LD1R", "LD1R_advsimd", 0xbfe0f000U, 0x0dc0c000U, ORLIX_TCTI_DECODE_SIMD_LOAD_REPLICATE, true, 1U, 1U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_REPLICATE, false) \
	X(2474U, "LD3R_asisdlsop_RX3_r", "LD3R", "LD3R_advsimd", 0xbfe0f000U, 0x0dc0e000U, ORLIX_TCTI_DECODE_SIMD_LOAD_REPLICATE, true, 3U, 1U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_REPLICATE, false) \
	X(2475U, "LD1_asisdlsop_B1_i1b", "LD1", "LD1_advsimd_sngl", 0xbfffe000U, 0x0ddf0000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, true, 1U, 1U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2476U, "LD3_asisdlsop_B3_i3b", "LD3", "LD3_advsimd_sngl", 0xbfffe000U, 0x0ddf2000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, true, 3U, 1U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2477U, "LD1_asisdlsop_H1_i1h", "LD1", "LD1_advsimd_sngl", 0xbfffe400U, 0x0ddf4000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, true, 1U, 2U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2478U, "LD3_asisdlsop_H3_i3h", "LD3", "LD3_advsimd_sngl", 0xbfffe400U, 0x0ddf6000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, true, 3U, 2U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2479U, "LD1_asisdlsop_S1_i1s", "LD1", "LD1_advsimd_sngl", 0xbfffec00U, 0x0ddf8000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, true, 1U, 4U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2480U, "LD1_asisdlsop_D1_i1d", "LD1", "LD1_advsimd_sngl", 0xbffffc00U, 0x0ddf8400U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, true, 1U, 8U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2481U, "LD3_asisdlsop_S3_i3s", "LD3", "LD3_advsimd_sngl", 0xbfffec00U, 0x0ddfa000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, true, 3U, 4U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2482U, "LD3_asisdlsop_D3_i3d", "LD3", "LD3_advsimd_sngl", 0xbffffc00U, 0x0ddfa400U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, true, 3U, 8U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2483U, "LD1R_asisdlsop_R1_i", "LD1R", "LD1R_advsimd", 0xbffff000U, 0x0ddfc000U, ORLIX_TCTI_DECODE_SIMD_LOAD_REPLICATE, true, 1U, 1U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_REPLICATE, false) \
	X(2484U, "LD3R_asisdlsop_R3_i", "LD3R", "LD3R_advsimd", 0xbffff000U, 0x0ddfe000U, ORLIX_TCTI_DECODE_SIMD_LOAD_REPLICATE, true, 3U, 1U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_REPLICATE, false) \
	X(2485U, "LD2_asisdlsop_BX2_r2b", "LD2", "LD2_advsimd_sngl", 0xbfe0e000U, 0x0de00000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, true, 2U, 1U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2486U, "LD4_asisdlsop_BX4_r4b", "LD4", "LD4_advsimd_sngl", 0xbfe0e000U, 0x0de02000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, true, 4U, 1U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2487U, "LD2_asisdlsop_HX2_r2h", "LD2", "LD2_advsimd_sngl", 0xbfe0e400U, 0x0de04000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, true, 2U, 2U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2488U, "LD4_asisdlsop_HX4_r4h", "LD4", "LD4_advsimd_sngl", 0xbfe0e400U, 0x0de06000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, true, 4U, 2U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2489U, "LD2_asisdlsop_SX2_r2s", "LD2", "LD2_advsimd_sngl", 0xbfe0ec00U, 0x0de08000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, true, 2U, 4U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2490U, "LD2_asisdlsop_DX2_r2d", "LD2", "LD2_advsimd_sngl", 0xbfe0fc00U, 0x0de08400U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, true, 2U, 8U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2491U, "LD4_asisdlsop_SX4_r4s", "LD4", "LD4_advsimd_sngl", 0xbfe0ec00U, 0x0de0a000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, true, 4U, 4U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2492U, "LD4_asisdlsop_DX4_r4d", "LD4", "LD4_advsimd_sngl", 0xbfe0fc00U, 0x0de0a400U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, true, 4U, 8U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2493U, "LD2R_asisdlsop_RX2_r", "LD2R", "LD2R_advsimd", 0xbfe0f000U, 0x0de0c000U, ORLIX_TCTI_DECODE_SIMD_LOAD_REPLICATE, true, 2U, 1U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_REPLICATE, false) \
	X(2494U, "LD4R_asisdlsop_RX4_r", "LD4R", "LD4R_advsimd", 0xbfe0f000U, 0x0de0e000U, ORLIX_TCTI_DECODE_SIMD_LOAD_REPLICATE, true, 4U, 1U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_REPLICATE, false) \
	X(2495U, "LD2_asisdlsop_B2_i2b", "LD2", "LD2_advsimd_sngl", 0xbfffe000U, 0x0dff0000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, true, 2U, 1U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2496U, "LD4_asisdlsop_B4_i4b", "LD4", "LD4_advsimd_sngl", 0xbfffe000U, 0x0dff2000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, true, 4U, 1U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2497U, "LD2_asisdlsop_H2_i2h", "LD2", "LD2_advsimd_sngl", 0xbfffe400U, 0x0dff4000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, true, 2U, 2U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2498U, "LD4_asisdlsop_H4_i4h", "LD4", "LD4_advsimd_sngl", 0xbfffe400U, 0x0dff6000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, true, 4U, 2U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2499U, "LD2_asisdlsop_S2_i2s", "LD2", "LD2_advsimd_sngl", 0xbfffec00U, 0x0dff8000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, true, 2U, 4U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2500U, "LD2_asisdlsop_D2_i2d", "LD2", "LD2_advsimd_sngl", 0xbffffc00U, 0x0dff8400U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, true, 2U, 8U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2501U, "LD4_asisdlsop_S4_i4s", "LD4", "LD4_advsimd_sngl", 0xbfffec00U, 0x0dffa000U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, true, 4U, 4U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2502U, "LD4_asisdlsop_D4_i4d", "LD4", "LD4_advsimd_sngl", 0xbffffc00U, 0x0dffa400U, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE, true, 4U, 8U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE, false) \
	X(2503U, "LD2R_asisdlsop_R2_i", "LD2R", "LD2R_advsimd", 0xbffff000U, 0x0dffc000U, ORLIX_TCTI_DECODE_SIMD_LOAD_REPLICATE, true, 2U, 1U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_REPLICATE, false) \
	X(2504U, "LD4R_asisdlsop_R4_i", "LD4R", "LD4R_advsimd", 0xbffff000U, 0x0dffe000U, ORLIX_TCTI_DECODE_SIMD_LOAD_REPLICATE, true, 4U, 1U, 8U, 16U, ORLIX_TCTI_MEMORY_INDEX_POST, ORLIX_TCTI_ADVSIMD_STRUCTURE_REPLICATE, false)

static const struct orlix_tcti_advsimd_structure_contract
	orlix_tcti_advsimd_structure_contracts[] = {
#define ORLIX_TCTI_ADVSIMD_STRUCTURE_CONTRACT_ROW(ordinal, leaf_id, mnemonic, \
	operation_id, mask, pattern, decode_class, load, structure_count, \
	access_size, q0_semantic_width, q1_semantic_width, index_mode, \
	lane_shape, interleaved) \
	{ ordinal, leaf_id, mnemonic, operation_id, mask, pattern, decode_class, \
	  load, structure_count, access_size, q0_semantic_width, \
	  q1_semantic_width, index_mode, lane_shape, interleaved },
	ORLIX_TCTI_ADVSIMD_STRUCTURE_CONTRACT_ROWS(ORLIX_TCTI_ADVSIMD_STRUCTURE_CONTRACT_ROW)
#undef ORLIX_TCTI_ADVSIMD_STRUCTURE_CONTRACT_ROW
};

/*
 * Every execution claim below enters through the same EL0 resume path as an
 * ordinary hosted guest.  The terminating SVC makes the structured result
 * distinguish successful execution from a decoder-only observation.
 */
static unsigned long orlix_tcti_advsimd_structure_map_instruction(struct kunit *test,
							      u32 instruction)
{
	const u32 program[] = { instruction, ORLIX_TCTI_ADVSIMD_STRUCTURE_SVC };
	unsigned long mapped;
	int ret;

	mapped = ksys_mmap_pgoff(0, PAGE_SIZE, PROT_READ | PROT_WRITE,
				 MAP_PRIVATE | MAP_ANONYMOUS, -1, 0);
	KUNIT_ASSERT_FALSE(test, IS_ERR_VALUE(mapped));
	ret = orlix_tcti_write_user_data(current->mm, mapped, program, sizeof(program));
	KUNIT_ASSERT_EQ(test, 0, ret);
	ret = sys_mprotect(mapped, PAGE_SIZE, PROT_READ | PROT_EXEC);
	KUNIT_ASSERT_EQ(test, 0, ret);
	return mapped;
}

static struct orlix_tcti_result orlix_tcti_advsimd_structure_resume(
	struct kunit *test, u32 instruction, struct pt_regs *regs,
	unsigned long *mapped)
{
	struct orlix_tcti_result result;

	*mapped = orlix_tcti_advsimd_structure_map_instruction(test, instruction);
	regs->pc = *mapped;
	regs->pstate |= PSR_MODE_EL0t;
	regs->syscallno = NO_SYSCALL;
	result = orlix_tcti_resume_user(current, regs, current->mm);
	KUNIT_EXPECT_EQ(test, ORLIX_TCTI_EXIT_SYSCALL, result.reason);
	KUNIT_EXPECT_EQ(test, 0L, result.status);
	KUNIT_EXPECT_EQ(test, ORLIX_TCTI_ADVSIMD_STRUCTURE_SVC, result.instruction);
	KUNIT_EXPECT_EQ(test, *mapped + 2 * sizeof(u32), result.pc);
	KUNIT_EXPECT_EQ(test, *mapped + 2 * sizeof(u32), regs->pc);
	return result;
}

static void orlix_tcti_advsimd_structure_initialize_state(struct pt_regs *regs,
						     u32 instruction)
{
	unsigned int index;

	for (index = 0; index < ARRAY_SIZE(regs->regs); index++)
		regs->regs[index] = 0x8192a3b4c5d6e700ULL ^
			((u64)instruction << 9) ^ index;
	regs->pc = 0x123456789000ULL;
	regs->sp = 0x23456789a000ULL;
	regs->pstate = PSR_MODE_EL0t | PSR_N_BIT | PSR_C_BIT;
	regs->orig_x0 = 0xd1b54a32d192ed03ULL;
	regs->syscallno = NO_SYSCALL;
	regs->unused = 0x6d5a56c3U;
	for (index = 0; index < ARRAY_SIZE(current->thread.user_simd); index++)
		current->thread.user_simd[index] = 0xfedcba9876543210ULL ^
			((u64)instruction << 13) ^
			(0x0101010101010101ULL * index);
	current->thread.user_simd_valid = 0;
	current->thread.user_fpcr = BIT(22) | BIT(24);
	current->thread.user_fpsr = BIT(4);
}

static u64 orlix_tcti_advsimd_structure_lane_mask(u8 size)
{
	return size == sizeof(u64) ? U64_MAX : GENMASK_ULL(size * 8 - 1, 0);
}

static u64 orlix_tcti_advsimd_structure_read_lane(const u64 *simd, u8 register_index,
						     u8 size, u8 lane)
{
	u8 byte = lane * size;

	return (simd[register_index * 2 + byte / sizeof(u64)] >>
		((byte % sizeof(u64)) * 8)) & orlix_tcti_advsimd_structure_lane_mask(size);
}

static void orlix_tcti_advsimd_structure_write_lane(u64 *simd, u8 register_index,
						      u8 size, u8 lane, u64 value)
{
	u8 byte = lane * size;
	u8 word = register_index * 2 + byte / sizeof(u64);
	u8 shift = (byte % sizeof(u64)) * 8;
	u64 mask = orlix_tcti_advsimd_structure_lane_mask(size) << shift;

	simd[word] = (simd[word] & ~mask) |
		((value & orlix_tcti_advsimd_structure_lane_mask(size)) << shift);
}

static u64 orlix_tcti_advsimd_structure_source_value(u32 ordinal, u8 offset,
							 u8 size)
{
	u64 value = 0;
	u8 byte;

	for (byte = 0; byte < size; byte++)
		value |= (u64)(u8)(ordinal + offset + byte) << (byte * 8);
	return value;
}

static u8 orlix_tcti_advsimd_structure_lane(u32 instruction, u8 access_size)
{
	u8 q = FIELD_GET(BIT(30), instruction);
	u8 s = FIELD_GET(BIT(12), instruction);

	switch (access_size) {
	case 1:
		return (q << 3) | (s << 2) |
			FIELD_GET(GENMASK(11, 10), instruction);
	case 2:
		return (q << 2) | (s << 1) | FIELD_GET(BIT(11), instruction);
	case 4:
		return (q << 1) | s;
	case 8:
		return q;
	default:
		return 0;
	}
}

static void orlix_tcti_advsimd_structure_expected_transfer(
	const struct orlix_tcti_advsimd_structure_contract *contract, u32 instruction,
	const u64 *before_simd, u64 *expected_simd, u8 *memory)
{
	u8 register_index = instruction & GENMASK(4, 0);
	u8 width = instruction & BIT(30) ? contract->q1_semantic_width :
		contract->q0_semantic_width;
	u8 lane = 0;
	u8 element;
	u8 structure;

	if (contract->lane_shape == ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE) {
		lane = orlix_tcti_advsimd_structure_lane(instruction,
			contract->access_size);
		for (structure = 0; structure < contract->structure_count; structure++) {
			u64 value = contract->load ?
				orlix_tcti_advsimd_structure_source_value(contract->ordinal,
					structure * contract->access_size,
					contract->access_size) :
				orlix_tcti_advsimd_structure_read_lane(before_simd,
					(register_index + structure) & 31,
					contract->access_size, lane);

			if (contract->load)
				orlix_tcti_advsimd_structure_write_lane(expected_simd,
					(register_index + structure) & 31, contract->access_size,
					lane, value);
			else
				memcpy(memory + structure * contract->access_size, &value,
					contract->access_size);
		}
		return;
	}

	if (contract->lane_shape == ORLIX_TCTI_ADVSIMD_STRUCTURE_REPLICATE) {
		for (structure = 0; structure < contract->structure_count; structure++)
			for (element = 0; element < width / contract->access_size;
			     element++)
				orlix_tcti_advsimd_structure_write_lane(expected_simd,
					(register_index + structure) & 31, contract->access_size,
					element,
					orlix_tcti_advsimd_structure_source_value(contract->ordinal,
						structure * contract->access_size,
						contract->access_size));
	} else {
		for (element = 0; element < width / contract->access_size; element++)
			for (structure = 0; structure < contract->structure_count;
			     structure++) {
				u8 offset = contract->interleaved ?
					(element * contract->structure_count + structure) *
					contract->access_size :
					(structure * (width / contract->access_size) + element) *
					contract->access_size;
				u64 value = contract->load ?
					orlix_tcti_advsimd_structure_source_value(contract->ordinal, offset,
						contract->access_size) :
					orlix_tcti_advsimd_structure_read_lane(before_simd,
						(register_index + structure) & 31,
						contract->access_size, element);

				if (contract->load)
					orlix_tcti_advsimd_structure_write_lane(expected_simd,
						(register_index + structure) & 31,
						contract->access_size, element, value);
				else
					memcpy(memory + offset, &value, contract->access_size);
			}
	}

	if (contract->load && !(instruction & BIT(30)) &&
	    contract->lane_shape != ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE)
		for (structure = 0; structure < contract->structure_count; structure++)
			expected_simd[((register_index + structure) & 31) * 2 + 1] = 0;
}

static void orlix_tcti_advsimd_structure_every_contract_row_executes(
	struct kunit *test)
{
	size_t index;

	KUNIT_ASSERT_NOT_NULL(test, current->mm);
	for (index = 0; index < ARRAY_SIZE(orlix_tcti_advsimd_structure_contracts);
	     index++) {
		const struct orlix_tcti_advsimd_structure_contract *contract =
			&orlix_tcti_advsimd_structure_contracts[index];
		unsigned int q;

		for (q = 0; q < 2; q++) {
			struct pt_regs regs = {};
			struct pt_regs expected_regs;
			u64 before_simd[ARRAY_SIZE(current->thread.user_simd)];
			u64 expected_simd[ARRAY_SIZE(current->thread.user_simd)];
			u8 memory[80];
			u8 observed[80];
			u32 instruction = contract->pattern | (q ? BIT(30) : 0) |
				(8U << 5) | 30U;
			unsigned long address;
			unsigned long mapped;
			u8 width = q ? contract->q1_semantic_width :
				contract->q0_semantic_width;
			u8 transfer_size = contract->lane_shape ==
				ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE || contract->lane_shape ==
				ORLIX_TCTI_ADVSIMD_STRUCTURE_REPLICATE ? contract->access_size :
				width;
			u8 total = contract->structure_count * transfer_size;
			u8 writeback_register = (instruction >> 16) & 31;
			u64 writeback = total + 7;
			int ret;

			KUNIT_ASSERT_LE_MSG(test, total, sizeof(memory) - 16,
				"ordinal=%u leaf=%s", contract->ordinal, contract->leaf_id);
			address = ksys_mmap_pgoff(0, PAGE_SIZE, PROT_READ | PROT_WRITE,
				MAP_PRIVATE | MAP_ANONYMOUS, -1, 0);
			KUNIT_ASSERT_FALSE(test, IS_ERR_VALUE(address));
			orlix_tcti_advsimd_structure_initialize_state(&regs, instruction);
			regs.regs[8] = address + 8;
			if (contract->index_mode == ORLIX_TCTI_MEMORY_INDEX_POST &&
			    writeback_register != 31) {
				KUNIT_ASSERT_NE_MSG(test, 8U, writeback_register,
					"ordinal=%u leaf=%s", contract->ordinal,
					contract->leaf_id);
				regs.regs[writeback_register] = writeback;
			}
			memcpy(before_simd, current->thread.user_simd, sizeof(before_simd));
			memcpy(expected_simd, before_simd, sizeof(expected_simd));
			memset(memory, 0xa5, sizeof(memory));
			for (ret = 0; ret < total; ret++)
				memory[8 + ret] = contract->ordinal + ret;
			KUNIT_ASSERT_EQ(test, 0, orlix_tcti_write_user_data(current->mm, address,
				memory, sizeof(memory)));
			orlix_tcti_advsimd_structure_expected_transfer(contract, instruction,
				before_simd, expected_simd, memory + 8);
			expected_regs = regs;
			if (contract->index_mode == ORLIX_TCTI_MEMORY_INDEX_POST)
				expected_regs.regs[8] += writeback_register == 31 ?
					total : writeback;
			orlix_tcti_advsimd_structure_resume(test, instruction, &regs, &mapped);
			expected_regs.pc = mapped + 2 * sizeof(u32);
			KUNIT_EXPECT_MEMEQ_MSG(test, &expected_regs, &regs, sizeof(regs),
				"ordinal=%u leaf=%s q=%u", contract->ordinal,
				contract->leaf_id, q);
			KUNIT_EXPECT_MEMEQ_MSG(test, expected_simd, current->thread.user_simd,
				sizeof(expected_simd), "ordinal=%u leaf=%s q=%u",
				contract->ordinal, contract->leaf_id, q);
			KUNIT_EXPECT_EQ_MSG(test, 1UL, current->thread.user_simd_valid,
				"ordinal=%u leaf=%s q=%u", contract->ordinal,
				contract->leaf_id, q);
			KUNIT_EXPECT_EQ_MSG(test, BIT(22) | BIT(24), current->thread.user_fpcr,
				"ordinal=%u leaf=%s q=%u", contract->ordinal,
				contract->leaf_id, q);
			KUNIT_EXPECT_EQ_MSG(test, BIT(4), current->thread.user_fpsr,
				"ordinal=%u leaf=%s q=%u", contract->ordinal,
				contract->leaf_id, q);
			KUNIT_ASSERT_EQ(test, 0, orlix_tcti_read_user_data(current->mm, address,
				observed, sizeof(observed)));
			if (contract->load) {
				KUNIT_EXPECT_MEMEQ_MSG(test, memory, observed, sizeof(memory),
					"ordinal=%u leaf=%s q=%u", contract->ordinal,
					contract->leaf_id, q);
			} else {
				KUNIT_EXPECT_MEMEQ_MSG(test, memory, observed, sizeof(memory),
					"ordinal=%u leaf=%s q=%u", contract->ordinal,
					contract->leaf_id, q);
			}
			KUNIT_EXPECT_EQ(test, 0, vm_munmap(mapped, PAGE_SIZE));
			KUNIT_EXPECT_EQ(test, 0, vm_munmap(address, PAGE_SIZE));
		}
	}
}

static void orlix_tcti_advsimd_structure_every_source_leaf_reaches_decoder(
	struct kunit *test)
{
	const struct orlix_tcti_target_instruction_artifact *artifact =
		orlix_tcti_target_instruction_artifact_canonical();
	size_t index;
	u32 observed = 0;

	KUNIT_ASSERT_NOT_NULL(test, artifact);
	KUNIT_ASSERT_GT(test, artifact->leaf_count,
			ORLIX_TCTI_ADVSIMD_STRUCTURE_LAST_SOURCE);
	KUNIT_ASSERT_EQ(test, ORLIX_TCTI_ADVSIMD_STRUCTURE_SOURCE_COUNT,
			ARRAY_SIZE(orlix_tcti_advsimd_structure_contracts));

	for (index = 0; index < ARRAY_SIZE(orlix_tcti_advsimd_structure_contracts);
	     index++) {
		const struct orlix_tcti_advsimd_structure_contract *expected =
			&orlix_tcti_advsimd_structure_contracts[index];
		const struct orlix_tcti_target_instruction_artifact_leaf *leaf =
			&artifact->leaves[expected->ordinal];
		const char *leaf_id = orlix_tcti_advsimd_structure_artifact_string(
			artifact, leaf->name_offset);
		const char *mnemonic = orlix_tcti_advsimd_structure_artifact_string(
			artifact, leaf->mnemonic_offset);
		const char *operation_id = orlix_tcti_advsimd_structure_artifact_string(
			artifact, leaf->operation_offset);
		struct orlix_tcti_decoded_instruction q0;
		struct orlix_tcti_decoded_instruction q1;

		KUNIT_EXPECT_EQ_MSG(test, ORLIX_TCTI_ADVSIMD_STRUCTURE_FIRST_SOURCE + index,
			expected->ordinal, "contract index=%zu", index);
		KUNIT_ASSERT_NOT_NULL_MSG(test, leaf_id, "ordinal=%u",
			expected->ordinal);
		KUNIT_ASSERT_NOT_NULL_MSG(test, mnemonic, "ordinal=%u",
			expected->ordinal);
		KUNIT_ASSERT_NOT_NULL_MSG(test, operation_id, "ordinal=%u",
			expected->ordinal);
		KUNIT_EXPECT_STREQ_MSG(test, expected->leaf_id, leaf_id,
			"ordinal=%u", expected->ordinal);
		KUNIT_EXPECT_STREQ_MSG(test, expected->mnemonic, mnemonic,
			"ordinal=%u leaf=%s", expected->ordinal, expected->leaf_id);
		KUNIT_EXPECT_STREQ_MSG(test, expected->operation_id, operation_id,
			"ordinal=%u leaf=%s", expected->ordinal, expected->leaf_id);
		KUNIT_EXPECT_EQ_MSG(test, expected->mask, leaf->encoding_mask,
			"ordinal=%u leaf=%s", expected->ordinal, expected->leaf_id);
		KUNIT_EXPECT_EQ_MSG(test, expected->pattern, leaf->encoding_pattern,
			"ordinal=%u leaf=%s", expected->ordinal, expected->leaf_id);

		q0 = orlix_tcti_decode_aarch64(expected->pattern);
		q1 = orlix_tcti_decode_aarch64(expected->pattern | BIT(30));
		KUNIT_EXPECT_EQ_MSG(test, expected->decode_class, q0.decode_class,
			"ordinal=%u leaf=%s q=0", expected->ordinal, expected->leaf_id);
		KUNIT_EXPECT_EQ_MSG(test, expected->decode_class, q1.decode_class,
			"ordinal=%u leaf=%s q=1", expected->ordinal, expected->leaf_id);
		KUNIT_EXPECT_EQ_MSG(test, expected->pattern, q0.instruction,
			"ordinal=%u leaf=%s q=0", expected->ordinal, expected->leaf_id);
		KUNIT_EXPECT_EQ_MSG(test, expected->pattern | BIT(30), q1.instruction,
			"ordinal=%u leaf=%s q=1", expected->ordinal, expected->leaf_id);
		KUNIT_EXPECT_EQ_MSG(test, expected->load, q0.load,
			"ordinal=%u leaf=%s", expected->ordinal, expected->leaf_id);
		KUNIT_EXPECT_EQ_MSG(test, expected->structure_count,
			q0.simd_structure_count, "ordinal=%u leaf=%s",
			expected->ordinal, expected->leaf_id);
		KUNIT_EXPECT_EQ_MSG(test, expected->access_size, q0.access_size,
			"ordinal=%u leaf=%s", expected->ordinal, expected->leaf_id);
		if (expected->lane_shape == ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE) {
			/* The current decoder exposes lane shape, not vector width. */
			KUNIT_EXPECT_EQ_MSG(test, 0U, q0.result_size,
				"ordinal=%u leaf=%s q=0", expected->ordinal,
				expected->leaf_id);
			KUNIT_EXPECT_EQ_MSG(test, 0U, q1.result_size,
				"ordinal=%u leaf=%s q=1", expected->ordinal,
				expected->leaf_id);
		} else {
			KUNIT_EXPECT_EQ_MSG(test, expected->q0_semantic_width,
				q0.result_size, "ordinal=%u leaf=%s q=0",
				expected->ordinal, expected->leaf_id);
			KUNIT_EXPECT_EQ_MSG(test, expected->q1_semantic_width,
				q1.result_size, "ordinal=%u leaf=%s q=1",
				expected->ordinal, expected->leaf_id);
		}
		KUNIT_EXPECT_EQ_MSG(test, expected->index_mode, q0.memory_index_mode,
			"ordinal=%u leaf=%s", expected->ordinal, expected->leaf_id);
		KUNIT_EXPECT_EQ_MSG(test, expected->interleaved, q0.simd_interleaved,
			"ordinal=%u leaf=%s", expected->ordinal, expected->leaf_id);
		KUNIT_EXPECT_EQ_MSG(test,
			expected->lane_shape == ORLIX_TCTI_ADVSIMD_STRUCTURE_REPLICATE,
			q0.simd_replicate, "ordinal=%u leaf=%s", expected->ordinal,
			expected->leaf_id);
		if (expected->lane_shape == ORLIX_TCTI_ADVSIMD_STRUCTURE_LANE)
			KUNIT_EXPECT_FALSE_MSG(test, q0.simd_replicate,
				"ordinal=%u leaf=%s lane form", expected->ordinal,
				expected->leaf_id);
		observed++;
	}

	KUNIT_EXPECT_EQ(test, ORLIX_TCTI_ADVSIMD_STRUCTURE_SOURCE_COUNT, observed);
}


static void orlix_tcti_advsimd_structure_single_lane_writeback_and_pc(
	struct kunit *test)
{
	const u8 source[] = { 0x5a, 0x6b, 0x7c, 0x8d };
	struct pt_regs regs = {};
	struct orlix_tcti_decoded_instruction decoded;
	unsigned long address;
	unsigned long mapped;
	int ret;

	KUNIT_ASSERT_NOT_NULL(test, current->mm);
	address = ksys_mmap_pgoff(0, PAGE_SIZE, PROT_READ | PROT_WRITE,
				 MAP_PRIVATE | MAP_ANONYMOUS, -1, 0);
	KUNIT_ASSERT_FALSE(test, IS_ERR_VALUE(address));
	KUNIT_ASSERT_EQ(test, 0,
		orlix_tcti_write_user_data(current->mm, address, source, sizeof(source)));

	/* LD4 {v31.b-v2.b}[8], [x8], #4. */
	decoded = orlix_tcti_decode_aarch64(0x4d60211fU);
	KUNIT_ASSERT_EQ(test, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE,
			decoded.decode_class);
	KUNIT_EXPECT_EQ(test, 4, decoded.simd_structure_count);
	KUNIT_EXPECT_EQ(test, ORLIX_TCTI_MEMORY_INDEX_POST,
			decoded.memory_index_mode);
	current->thread.user_simd[31 * 2 + 1] = 0;
	current->thread.user_simd[0] = 0;
	current->thread.user_simd[1] = 0;
	current->thread.user_simd[2] = 0;
	regs.regs[8] = address;

	orlix_tcti_advsimd_structure_resume(test, 0x4d60211fU, &regs, &mapped);
	KUNIT_EXPECT_EQ(test, address + sizeof(source), regs.regs[8]);
	KUNIT_EXPECT_EQ(test, (u64)source[0],
			current->thread.user_simd[31 * 2 + 1] & 0xffULL);
	KUNIT_EXPECT_EQ(test, (u64)source[1],
			current->thread.user_simd[0] & 0xffULL);
	KUNIT_EXPECT_EQ(test, (u64)source[2],
			current->thread.user_simd[1] & 0xffULL);
	KUNIT_EXPECT_EQ(test, (u64)source[3],
			current->thread.user_simd[2] & 0xffULL);

	KUNIT_EXPECT_EQ(test, 0, vm_munmap(mapped, PAGE_SIZE));
	KUNIT_EXPECT_EQ(test, 0, vm_munmap(address, PAGE_SIZE));
}

static void orlix_tcti_advsimd_structure_replicate_and_pc(struct kunit *test)
{
	const u8 source[] = { 0x19, 0x2a, 0x3b, 0x4c };
	struct pt_regs regs = {};
	struct orlix_tcti_decoded_instruction decoded;
	unsigned long address;
	unsigned long mapped;
	int ret;

	KUNIT_ASSERT_NOT_NULL(test, current->mm);
	address = ksys_mmap_pgoff(0, PAGE_SIZE, PROT_READ | PROT_WRITE,
				 MAP_PRIVATE | MAP_ANONYMOUS, -1, 0);
	KUNIT_ASSERT_FALSE(test, IS_ERR_VALUE(address));
	KUNIT_ASSERT_EQ(test, 0,
		orlix_tcti_write_user_data(current->mm, address, source, sizeof(source)));

	/* LD4R {v30.16b-v1.16b}, [x8]. */
	decoded = orlix_tcti_decode_aarch64(0x4d60e11eU);
	KUNIT_ASSERT_EQ(test, ORLIX_TCTI_DECODE_SIMD_LOAD_REPLICATE,
			decoded.decode_class);
	KUNIT_EXPECT_EQ(test, 4, decoded.simd_structure_count);
	regs.regs[8] = address;

	orlix_tcti_advsimd_structure_resume(test, 0x4d60e11eU, &regs, &mapped);
	KUNIT_EXPECT_EQ(test, address, regs.regs[8]);
	KUNIT_EXPECT_EQ(test, 0x1919191919191919ULL,
			current->thread.user_simd[30 * 2]);
	KUNIT_EXPECT_EQ(test, 0x2a2a2a2a2a2a2a2aULL,
			current->thread.user_simd[31 * 2]);
	KUNIT_EXPECT_EQ(test, 0x3b3b3b3b3b3b3b3bULL,
			current->thread.user_simd[0]);
	KUNIT_EXPECT_EQ(test, 0x4c4c4c4c4c4c4c4cULL,
			current->thread.user_simd[1]);

	KUNIT_EXPECT_EQ(test, 0, vm_munmap(mapped, PAGE_SIZE));
	KUNIT_EXPECT_EQ(test, 0, vm_munmap(address, PAGE_SIZE));
}

static void orlix_tcti_advsimd_structure_fault_preserves_pc_and_writeback(
	struct kunit *test)
{
	struct pt_regs regs = {};
	struct pt_regs before_regs;
	struct orlix_tcti_decoded_instruction decoded;
	struct orlix_tcti_result result;
	unsigned long address;
	unsigned long mapped;
	u64 before_simd[ARRAY_SIZE(current->thread.user_simd)];
	unsigned long before_valid;
	unsigned long before_fpcr;
	unsigned long before_fpsr;
	int ret;

	KUNIT_ASSERT_NOT_NULL(test, current->mm);
	address = ksys_mmap_pgoff(0, 2 * PAGE_SIZE, PROT_READ | PROT_WRITE,
				 MAP_PRIVATE | MAP_ANONYMOUS, -1, 0);
	KUNIT_ASSERT_FALSE(test, IS_ERR_VALUE(address));
	KUNIT_ASSERT_EQ(test, 0,
		sys_mprotect(address + PAGE_SIZE, PAGE_SIZE, PROT_NONE));

	/* LD2 {v3.8h, v4.8h}, [x10].  The first transfer faults. */
	decoded = orlix_tcti_decode_aarch64(0x0c408543U);
	KUNIT_ASSERT_EQ(test, ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_MULTIPLE_STRUCTURE,
			decoded.decode_class);
	orlix_tcti_advsimd_structure_initialize_state(&regs, 0x0c408543U);
	regs.regs[10] = address + PAGE_SIZE;
	before_regs = regs;
	memcpy(before_simd, current->thread.user_simd, sizeof(before_simd));
	before_valid = current->thread.user_simd_valid;
	before_fpcr = current->thread.user_fpcr;
	before_fpsr = current->thread.user_fpsr;

	mapped = orlix_tcti_advsimd_structure_map_instruction(test, 0x0c408543U);
	regs.pc = mapped;
	before_regs.pc = mapped;
	regs.pstate |= PSR_MODE_EL0t;
	regs.syscallno = NO_SYSCALL;
	result = orlix_tcti_resume_user(current, &regs, current->mm);
	KUNIT_EXPECT_EQ(test, ORLIX_TCTI_EXIT_USER_FAULT, result.reason);
	KUNIT_EXPECT_EQ(test, -EFAULT, result.status);
	KUNIT_EXPECT_EQ(test, address + PAGE_SIZE, result.fault_address);
	KUNIT_EXPECT_EQ(test, ORLIX_TCTI_ACCESS_READ, result.fault_access);
	KUNIT_EXPECT_EQ(test, mapped, result.pc);
	KUNIT_EXPECT_MEMEQ(test, &before_regs, &regs, sizeof(regs));
	KUNIT_EXPECT_MEMEQ(test, before_simd, current->thread.user_simd,
			   sizeof(before_simd));
	KUNIT_EXPECT_EQ(test, before_valid, current->thread.user_simd_valid);
	KUNIT_EXPECT_EQ(test, before_fpcr, current->thread.user_fpcr);
	KUNIT_EXPECT_EQ(test, before_fpsr, current->thread.user_fpsr);

	KUNIT_EXPECT_EQ(test, 0, vm_munmap(mapped, PAGE_SIZE));
	KUNIT_EXPECT_EQ(test, 0, vm_munmap(address, 2 * PAGE_SIZE));
}

static void orlix_tcti_advsimd_structure_write_fault_preserves_full_state(
	struct kunit *test)
{
	struct pt_regs regs = {};
	struct pt_regs before_regs;
	struct orlix_tcti_result result;
	unsigned long address;
	unsigned long mapped;
	u64 before_simd[ARRAY_SIZE(current->thread.user_simd)];
	u8 before_memory[32];
	u8 observed[32];
	unsigned long before_valid;
	unsigned long before_fpcr;
	unsigned long before_fpsr;

	KUNIT_ASSERT_NOT_NULL(test, current->mm);
	address = ksys_mmap_pgoff(0, 2 * PAGE_SIZE, PROT_READ | PROT_WRITE,
		MAP_PRIVATE | MAP_ANONYMOUS, -1, 0);
	KUNIT_ASSERT_FALSE(test, IS_ERR_VALUE(address));
	memset(before_memory, 0x3c, sizeof(before_memory));
	KUNIT_ASSERT_EQ(test, 0, orlix_tcti_write_user_data(current->mm,
		address + PAGE_SIZE, before_memory, sizeof(before_memory)));
	KUNIT_ASSERT_EQ(test, 0, sys_mprotect(address + PAGE_SIZE, PAGE_SIZE,
		PROT_NONE));

	/* ST2 {v3.8h, v4.8h}, [x10].  The first transfer must not commit. */
	orlix_tcti_advsimd_structure_initialize_state(&regs, 0x0c008543U);
	regs.regs[10] = address + PAGE_SIZE;
	before_regs = regs;
	memcpy(before_simd, current->thread.user_simd, sizeof(before_simd));
	before_valid = current->thread.user_simd_valid;
	before_fpcr = current->thread.user_fpcr;
	before_fpsr = current->thread.user_fpsr;
	mapped = orlix_tcti_advsimd_structure_map_instruction(test, 0x0c008543U);
	regs.pc = mapped;
	before_regs.pc = mapped;
	result = orlix_tcti_resume_user(current, &regs, current->mm);
	KUNIT_EXPECT_EQ(test, ORLIX_TCTI_EXIT_USER_FAULT, result.reason);
	KUNIT_EXPECT_EQ(test, -EFAULT, result.status);
	KUNIT_EXPECT_EQ(test, address + PAGE_SIZE, result.fault_address);
	KUNIT_EXPECT_EQ(test, ORLIX_TCTI_ACCESS_WRITE, result.fault_access);
	KUNIT_EXPECT_EQ(test, mapped, result.pc);
	KUNIT_EXPECT_MEMEQ(test, &before_regs, &regs, sizeof(regs));
	KUNIT_EXPECT_MEMEQ(test, before_simd, current->thread.user_simd,
			   sizeof(before_simd));
	KUNIT_EXPECT_EQ(test, before_valid, current->thread.user_simd_valid);
	KUNIT_EXPECT_EQ(test, before_fpcr, current->thread.user_fpcr);
	KUNIT_EXPECT_EQ(test, before_fpsr, current->thread.user_fpsr);
	KUNIT_ASSERT_EQ(test, 0, sys_mprotect(address + PAGE_SIZE, PAGE_SIZE,
		PROT_READ | PROT_WRITE));
	KUNIT_ASSERT_EQ(test, 0, orlix_tcti_read_user_data(current->mm,
		address + PAGE_SIZE, observed, sizeof(observed)));
	KUNIT_EXPECT_MEMEQ(test, before_memory, observed, sizeof(observed));
	KUNIT_EXPECT_EQ(test, 0, vm_munmap(mapped, PAGE_SIZE));
	KUNIT_EXPECT_EQ(test, 0, vm_munmap(address, 2 * PAGE_SIZE));
}

static void orlix_tcti_advsimd_structure_reserved_encodings_reject(
	struct kunit *test)
{
	const u32 reserved[] = { 0x0d008800U, 0x0c001000U };
	size_t index;

	/* Single-structure 32-bit lane form with size=2 is reserved. */
	KUNIT_EXPECT_EQ(test, ORLIX_TCTI_DECODE_UNSUPPORTED,
		orlix_tcti_decode_aarch64(reserved[0]).decode_class);
	/* The multiple-structure opcode holes are not decoded as structures. */
	KUNIT_EXPECT_EQ(test, ORLIX_TCTI_DECODE_UNSUPPORTED,
		orlix_tcti_decode_aarch64(reserved[1]).decode_class);

	for (index = 0; index < ARRAY_SIZE(reserved); index++) {
		struct pt_regs regs = {};
		struct orlix_tcti_result result;
		unsigned long mapped;

		mapped = orlix_tcti_advsimd_structure_map_instruction(test,
								reserved[index]);
		regs.pc = mapped;
		regs.pstate = PSR_MODE_EL0t;
		regs.syscallno = NO_SYSCALL;
		result = orlix_tcti_resume_user(current, &regs, current->mm);
		KUNIT_EXPECT_EQ(test, ORLIX_TCTI_EXIT_UNSUPPORTED_INSTRUCTION,
				result.reason);
		KUNIT_EXPECT_EQ(test, -EOPNOTSUPP, result.status);
		KUNIT_EXPECT_EQ(test, reserved[index], result.instruction);
		KUNIT_EXPECT_EQ(test, mapped, result.pc);
		KUNIT_EXPECT_EQ(test, mapped, regs.pc);
		KUNIT_EXPECT_EQ(test, 0, vm_munmap(mapped, PAGE_SIZE));
	}
}

static struct kunit_case orlix_tcti_advsimd_structure_cases[] = {
	KUNIT_CASE(orlix_tcti_advsimd_structure_every_source_leaf_reaches_decoder),
	KUNIT_CASE(orlix_tcti_advsimd_structure_every_contract_row_executes),
	KUNIT_CASE(orlix_tcti_advsimd_structure_single_lane_writeback_and_pc),
	KUNIT_CASE(orlix_tcti_advsimd_structure_replicate_and_pc),
	KUNIT_CASE(orlix_tcti_advsimd_structure_fault_preserves_pc_and_writeback),
	KUNIT_CASE(orlix_tcti_advsimd_structure_write_fault_preserves_full_state),
	KUNIT_CASE(orlix_tcti_advsimd_structure_reserved_encodings_reject),
	{}
};

static struct kunit_suite orlix_tcti_advsimd_structure_suite = {
	.name = "orlix-tcti-advsimd-structure-source-bound",
	.init = orlix_tcti_advsimd_structure_test_init,
	.exit = orlix_tcti_advsimd_structure_test_exit,
	.test_cases = orlix_tcti_advsimd_structure_cases,
};

kunit_test_suite(orlix_tcti_advsimd_structure_suite);
