/* SPDX-License-Identifier: GPL-2.0-only */
#ifndef ORLIX_TCTI_TARGET_PROOF_INGESTION_H
#define ORLIX_TCTI_TARGET_PROOF_INGESTION_H

#ifndef __KERNEL__
#include <stdbool.h>
#endif

#include "target_proof_registry.h"
#include "target_native_proof_contract.h"

#define ORLIX_TCTI_TARGET_PROOF_BUILD_ID_MAX ORLIX_TCTI_NATIVE_BUILD_ID_MAX

enum orlix_tcti_target_kselftest_result_state {
	ORLIX_TCTI_TARGET_KSELFTEST_UNEXECUTED,
	ORLIX_TCTI_TARGET_KSELFTEST_PASSED,
	ORLIX_TCTI_TARGET_KSELFTEST_FAILED,
	ORLIX_TCTI_TARGET_KSELFTEST_SKIPPED,
	ORLIX_TCTI_TARGET_KSELFTEST_INCOMPLETE,
};

enum orlix_tcti_target_proof_ingestion_error {
	ORLIX_TCTI_TARGET_PROOF_INGEST_OK,
	ORLIX_TCTI_TARGET_PROOF_INGEST_INVALID,
	ORLIX_TCTI_TARGET_PROOF_INGEST_REPLAY,
	ORLIX_TCTI_TARGET_PROOF_INGEST_UNKNOWN,
	ORLIX_TCTI_TARGET_PROOF_INGEST_STALE_SOURCE,
	ORLIX_TCTI_TARGET_PROOF_INGEST_FAMILY_MISMATCH,
	ORLIX_TCTI_TARGET_PROOF_INGEST_CLASSIFICATION_MISMATCH,
	ORLIX_TCTI_TARGET_PROOF_INGEST_CONDITION_MISMATCH,
	ORLIX_TCTI_TARGET_PROOF_INGEST_DDI_MISMATCH,
	ORLIX_TCTI_TARGET_PROOF_INGEST_BUILD_MISMATCH,
	ORLIX_TCTI_TARGET_PROOF_INGEST_PROFILE_MISMATCH,
	ORLIX_TCTI_TARGET_PROOF_INGEST_SUITE_MISMATCH,
	ORLIX_TCTI_TARGET_PROOF_INGEST_CASE_MISMATCH,
	ORLIX_TCTI_TARGET_PROOF_INGEST_PATH_MISMATCH,
	ORLIX_TCTI_TARGET_PROOF_INGEST_OBLIGATION_MISMATCH,
	ORLIX_TCTI_TARGET_PROOF_INGEST_TYPE_SUBSTITUTION,
	ORLIX_TCTI_TARGET_PROOF_INGEST_NON_PRODUCTION,
	ORLIX_TCTI_TARGET_PROOF_INGEST_RESULT_NOT_PASSED,
	ORLIX_TCTI_TARGET_PROOF_INGEST_NOT_APPLICABLE,
};

struct orlix_tcti_target_kselftest_result;
struct orlix_tcti_target_proof_ingestion_ledger;

struct orlix_tcti_target_proof_ingestion_summary {
	size_t accepted_records;
	size_t native_passed;
	size_t kselftest_passed;
	size_t rejected;
};

struct orlix_tcti_target_proof_ingestion_ledger *
orlix_tcti_target_proof_ingestion_ledger_create(size_t capacity);
void orlix_tcti_target_proof_ingestion_ledger_destroy(
	struct orlix_tcti_target_proof_ingestion_ledger *ledger);
int orlix_tcti_target_proof_ingestion_summary(
	const struct orlix_tcti_target_proof_ingestion_ledger *ledger,
	struct orlix_tcti_target_proof_ingestion_summary *summary);

int orlix_tcti_target_proof_ingest_native(
	struct orlix_tcti_target_proof_ingestion_ledger *ledger,
	struct orlix_tcti_native_wire_record *record,
	enum orlix_tcti_target_proof_ingestion_error *error);
int orlix_tcti_target_proof_ingest_kselftest(
	struct orlix_tcti_target_proof_ingestion_ledger *ledger,
	struct orlix_tcti_target_kselftest_result *result,
	enum orlix_tcti_target_proof_ingestion_error *error);

#endif /* ORLIX_TCTI_TARGET_PROOF_INGESTION_H */
