/* SPDX-License-Identifier: GPL-2.0-only */
#ifndef ORLIX_TCTI_TARGET_CONDITION_FORMAT_H
#define ORLIX_TCTI_TARGET_CONDITION_FORMAT_H

/* TCND version 1 is the bounded, length-delimited condition byte format. */
#define ORLIX_TCTI_TARGET_CONDITION_MAX_SERIALIZED_BYTES (1024U * 1024U)
#define ORLIX_TCTI_TARGET_CONDITION_MAX_DEPTH 256U

enum orlix_tcti_target_condition_tag {
	ORLIX_TCTI_TARGET_CONDITION_BOOL = 0x01,
	ORLIX_TCTI_TARGET_CONDITION_FEATURE = 0x02,
	ORLIX_TCTI_TARGET_CONDITION_OPERAND = 0x03,
	ORLIX_TCTI_TARGET_CONDITION_VALUE = 0x04,
	ORLIX_TCTI_TARGET_CONDITION_SET = 0x05,
	ORLIX_TCTI_TARGET_CONDITION_NOT = 0x06,
	ORLIX_TCTI_TARGET_CONDITION_AND = 0x07,
	ORLIX_TCTI_TARGET_CONDITION_OR = 0x08,
	ORLIX_TCTI_TARGET_CONDITION_EQ = 0x09,
	ORLIX_TCTI_TARGET_CONDITION_NE = 0x0a,
	ORLIX_TCTI_TARGET_CONDITION_IN = 0x0b,
};

#endif /* ORLIX_TCTI_TARGET_CONDITION_FORMAT_H */
