#!/usr/bin/env python3
"""Generate docs/index.md from Orlix ontology page frontmatter."""

from __future__ import annotations

import re
import sys
from pathlib import Path


META = {"AGENTS.md", "README.md", "index.md", "log.md", "ontology.md"}


def root_from_args() -> tuple[Path, bool]:
    args = [arg for arg in sys.argv[1:] if arg != "--check"]
    check = "--check" in sys.argv[1:]
    root = Path(args[0]).resolve() if args else Path(__file__).resolve().parents[4] / "docs"
    if not (root / "ontology.md").is_file():
        raise SystemExit(f"error: {root} is not an ontology brain")
    return root, check


def scalar(frontmatter: str, key: str) -> str:
    match = re.search(rf"^{re.escape(key)}:\s*[\"']?([^\n\"']+)[\"']?\s*$", frontmatter, re.MULTILINE)
    return match.group(1).strip() if match else ""


def generate(root: Path) -> str:
    groups: dict[str, list[tuple[str, str, str, str]]] = {}
    for path in sorted(root.rglob("*.md")):
        if path.name in META:
            continue
        text = path.read_text(encoding="utf-8")
        match = re.match(r"---\n(.*?)\n---\n", text, re.DOTALL)
        frontmatter = match.group(1) if match else ""
        heading = re.search(r"^#\s+(.+)$", text, re.MULTILINE)
        kind = scalar(frontmatter, "type") or "untyped"
        status = scalar(frontmatter, "status")
        summary = scalar(frontmatter, "summary")
        title = heading.group(1).strip() if heading else path.stem
        groups.setdefault(kind, []).append((title, path.relative_to(root).as_posix(), status, summary))

    output = [
        "---",
        "type: meta",
        "---",
        "",
        "# Orlix Knowledge Index",
        "",
        "This file is generated by `.agents/skills/orlix-docs-lint/scripts/build_index.py`. Edit canonical pages and regenerate it.",
    ]
    for kind in sorted(groups):
        output.extend(["", f"## {kind.replace('-', ' ').title()}", ""])
        for title, target, status, summary in sorted(groups[kind], key=lambda item: item[0].lower()):
            details = " · ".join(value for value in (status, summary) if value)
            output.append(f"- [{title}]({target})" + (f": {details}" if details else ""))
    output.extend(["", "## Meta", "", "- [Orientation](README.md)", "- [Ontology](ontology.md)", "- [Maintenance protocol](AGENTS.md)", "- [Change log](log.md)", ""])
    return "\n".join(output)


def main() -> int:
    root, check = root_from_args()
    target = root / "index.md"
    generated = generate(root)
    if check:
        if not target.is_file() or target.read_text(encoding="utf-8") != generated:
            print("index-drift: docs/index.md is stale")
            return 1
        print("index.md is current")
        return 0
    target.write_text(generated, encoding="utf-8")
    print(f"generated {target}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
