#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-only
"""Source-of-truth generator placeholder for Orlix TCTI gadgets.

Generated gadget tables must be deterministic and disposable. Manual edits to
generated output are invalid.
"""

import hashlib


def main() -> None:
    payload = b"orlix-tcti-gadget-generator-v0\n"
    print("/* SPDX-License-Identifier: GPL-2.0-only */")
    print("/* Generated by tcti-gadget-gen.py. Do not edit. */")
    print(f"#define ORLIX_TCTI_GADGET_GEN_SHA256 \"{hashlib.sha256(payload).hexdigest()}\"")


if __name__ == "__main__":
    main()
