/* SPDX-License-Identifier: GPL-2.0-only */
#ifndef ORLIX_TCTI_DECODE_AARCH64_H
#define ORLIX_TCTI_DECODE_AARCH64_H

#include <linux/types.h>

enum tcti_decode_class {
	TCTI_DECODE_UNSUPPORTED = 0,
	TCTI_DECODE_SVC,
	TCTI_DECODE_HINT,
	TCTI_DECODE_ADD_SUB_IMMEDIATE,
	TCTI_DECODE_ADD_SUB_SHIFTED_REGISTER,
	TCTI_DECODE_ADD_SUB_EXTENDED_REGISTER,
	TCTI_DECODE_ADD_SUB_WITH_CARRY,
	TCTI_DECODE_PC_RELATIVE_ADDRESS,
	TCTI_DECODE_UNCONDITIONAL_BRANCH_IMMEDIATE,
	TCTI_DECODE_UNCONDITIONAL_BRANCH_REGISTER,
	TCTI_DECODE_COMPARE_BRANCH_IMMEDIATE,
	TCTI_DECODE_TEST_BRANCH_IMMEDIATE,
	TCTI_DECODE_CONDITIONAL_BRANCH_IMMEDIATE,
	TCTI_DECODE_CONDITIONAL_COMPARE,
	TCTI_DECODE_CONDITIONAL_SELECT,
	TCTI_DECODE_LOAD_STORE_PAIR,
	TCTI_DECODE_LOAD_STORE_UNSIGNED_IMMEDIATE,
	TCTI_DECODE_LOAD_STORE_SIGNED_IMMEDIATE,
	TCTI_DECODE_LOAD_STORE_REGISTER_OFFSET,
	TCTI_DECODE_LOGICAL_SHIFTED_REGISTER,
	TCTI_DECODE_LOGICAL_IMMEDIATE,
	TCTI_DECODE_BITFIELD,
	TCTI_DECODE_EXTRACT,
	TCTI_DECODE_DATA_PROCESSING_1SOURCE,
	TCTI_DECODE_DATA_PROCESSING_2SOURCE,
	TCTI_DECODE_MULTIPLY_ADD_SUB,
	TCTI_DECODE_MOVE_WIDE_IMMEDIATE,
	TCTI_DECODE_SYSTEM_REGISTER,
	TCTI_DECODE_EXCLUSIVE_MONITOR_CLEAR,
	TCTI_DECODE_LOAD_STORE_EXCLUSIVE,
	TCTI_DECODE_SIMD_MODIFIED_IMMEDIATE,
	TCTI_DECODE_SIMD_VECTOR_ELEMENT_MOVE,
	TCTI_DECODE_SIMD_VECTOR_LOGICAL,
	TCTI_DECODE_SIMD_VECTOR_ARITHMETIC,
	TCTI_DECODE_SIMD_VECTOR_COMPARE,
	TCTI_DECODE_SIMD_VECTOR_REDUCTION,
	TCTI_DECODE_SIMD_LOAD_REPLICATE,
	TCTI_DECODE_FP_SCALAR_MOVE,
	TCTI_DECODE_FP_SCALAR_1SOURCE,
	TCTI_DECODE_FP_SCALAR_2SOURCE,
	TCTI_DECODE_FP_SCALAR_3SOURCE,
	TCTI_DECODE_FP_SCALAR_COMPARE,
	TCTI_DECODE_FP_CONDITIONAL_SELECT,
	TCTI_DECODE_FP_INT_CONVERT,
};

enum tcti_memory_index_mode {
	TCTI_MEMORY_INDEX_SIGNED_OFFSET = 0,
	TCTI_MEMORY_INDEX_PRE,
	TCTI_MEMORY_INDEX_POST,
};

enum tcti_logical_op {
	TCTI_LOGICAL_AND = 0,
	TCTI_LOGICAL_BIC,
	TCTI_LOGICAL_ORR,
	TCTI_LOGICAL_ORN,
	TCTI_LOGICAL_EOR,
	TCTI_LOGICAL_BSL,
	TCTI_LOGICAL_BIT,
	TCTI_LOGICAL_BIF,
};

enum tcti_simd_modified_immediate_op {
	TCTI_SIMD_MODIMM_MOVI = 0,
	TCTI_SIMD_MODIMM_MVNI,
	TCTI_SIMD_MODIMM_ORR,
	TCTI_SIMD_MODIMM_BIC,
};

enum tcti_simd_reduction_op {
	TCTI_SIMD_REDUCTION_UMAXV = 0,
	TCTI_SIMD_REDUCTION_ADDV,
	TCTI_SIMD_REDUCTION_ADDP,
};

enum tcti_simd_element_move_op {
	TCTI_SIMD_ELEMENT_MOVE_DUP = 0,
	TCTI_SIMD_ELEMENT_MOVE_XTN,
	TCTI_SIMD_ELEMENT_MOVE_UZP1,
	TCTI_SIMD_ELEMENT_MOVE_UZP2,
	TCTI_SIMD_ELEMENT_MOVE_TRN1,
	TCTI_SIMD_ELEMENT_MOVE_TRN2,
	TCTI_SIMD_ELEMENT_MOVE_ZIP1,
	TCTI_SIMD_ELEMENT_MOVE_ZIP2,
	TCTI_SIMD_ELEMENT_MOVE_UMOV,
	TCTI_SIMD_ELEMENT_MOVE_INS_GPR,
	TCTI_SIMD_ELEMENT_MOVE_SSHLL,
	TCTI_SIMD_ELEMENT_MOVE_USHLL,
	TCTI_SIMD_ELEMENT_MOVE_EXT,
};

enum tcti_move_wide_op {
	TCTI_MOVE_WIDE_MOVN = 0,
	TCTI_MOVE_WIDE_MOVZ,
	TCTI_MOVE_WIDE_MOVK,
};

enum tcti_branch_register_op {
	TCTI_BRANCH_REGISTER_BR = 0,
	TCTI_BRANCH_REGISTER_BLR,
	TCTI_BRANCH_REGISTER_RET,
};

enum tcti_system_register {
	TCTI_SYSTEM_REGISTER_TPIDR_EL0 = 0,
	TCTI_SYSTEM_REGISTER_NZCV,
	TCTI_SYSTEM_REGISTER_FPCR,
	TCTI_SYSTEM_REGISTER_FPSR,
};

enum tcti_conditional_select_op {
	TCTI_CONDITIONAL_SELECT_CSEL = 0,
	TCTI_CONDITIONAL_SELECT_CSINC,
	TCTI_CONDITIONAL_SELECT_CSINV,
	TCTI_CONDITIONAL_SELECT_CSNEG,
};

enum tcti_bitfield_op {
	TCTI_BITFIELD_SBFM = 0,
	TCTI_BITFIELD_BFM,
	TCTI_BITFIELD_UBFM,
};

enum tcti_data_processing_2source_op {
	TCTI_DP2_UDIV = 0,
	TCTI_DP2_SDIV,
	TCTI_DP2_LSLV,
	TCTI_DP2_LSRV,
	TCTI_DP2_ASRV,
	TCTI_DP2_RORV,
};

enum tcti_data_processing_1source_op {
	TCTI_DP1_CLZ = 0,
	TCTI_DP1_RBIT,
	TCTI_DP1_REV,
	TCTI_DP1_REV16,
};

enum tcti_simd_vector_arithmetic_op {
	TCTI_SIMD_ARITH_ADD = 0,
	TCTI_SIMD_ARITH_SUB,
	TCTI_SIMD_ARITH_SHADD,
	TCTI_SIMD_ARITH_UHADD,
	TCTI_SIMD_ARITH_SRHADD,
	TCTI_SIMD_ARITH_URHADD,
	TCTI_SIMD_ARITH_SHSUB,
	TCTI_SIMD_ARITH_UHSUB,
	TCTI_SIMD_ARITH_ADDP,
	TCTI_SIMD_ARITH_SADDW,
	TCTI_SIMD_ARITH_UADDW,
	TCTI_SIMD_ARITH_SSUBW,
	TCTI_SIMD_ARITH_USUBW,
	TCTI_SIMD_ARITH_SADDL,
	TCTI_SIMD_ARITH_UADDL,
	TCTI_SIMD_ARITH_SSUBL,
	TCTI_SIMD_ARITH_USUBL,
	TCTI_SIMD_ARITH_SMAXP,
	TCTI_SIMD_ARITH_UMAXP,
	TCTI_SIMD_ARITH_SMINP,
	TCTI_SIMD_ARITH_UMINP,
	TCTI_SIMD_ARITH_SQADD,
	TCTI_SIMD_ARITH_UQADD,
	TCTI_SIMD_ARITH_SQSUB,
	TCTI_SIMD_ARITH_UQSUB,
	TCTI_SIMD_ARITH_SQDMULH,
	TCTI_SIMD_ARITH_SQRDMULH,
	TCTI_SIMD_ARITH_MUL,
	TCTI_SIMD_ARITH_PMUL,
	TCTI_SIMD_ARITH_PMULL,
	TCTI_SIMD_ARITH_SMULL,
	TCTI_SIMD_ARITH_UMULL,
	TCTI_SIMD_ARITH_SMLAL,
	TCTI_SIMD_ARITH_UMLAL,
	TCTI_SIMD_ARITH_SMLSL,
	TCTI_SIMD_ARITH_UMLSL,
	TCTI_SIMD_ARITH_AESE,
	TCTI_SIMD_ARITH_AESD,
	TCTI_SIMD_ARITH_AESMC,
	TCTI_SIMD_ARITH_AESIMC,
	TCTI_SIMD_ARITH_MLA,
	TCTI_SIMD_ARITH_MLS,
	TCTI_SIMD_ARITH_SMAX,
	TCTI_SIMD_ARITH_UMAX,
	TCTI_SIMD_ARITH_SMIN,
	TCTI_SIMD_ARITH_UMIN,
	TCTI_SIMD_ARITH_SABD,
	TCTI_SIMD_ARITH_UABD,
	TCTI_SIMD_ARITH_SABA,
	TCTI_SIMD_ARITH_UABA,
	TCTI_SIMD_ARITH_SABDL,
	TCTI_SIMD_ARITH_UABDL,
	TCTI_SIMD_ARITH_SABAL,
	TCTI_SIMD_ARITH_UABAL,
	TCTI_SIMD_ARITH_ADDHN,
	TCTI_SIMD_ARITH_SUBHN,
	TCTI_SIMD_ARITH_RADDHN,
	TCTI_SIMD_ARITH_RSUBHN,
	TCTI_SIMD_ARITH_SQXTN,
	TCTI_SIMD_ARITH_UQXTN,
	TCTI_SIMD_ARITH_SQXTUN,
	TCTI_SIMD_ARITH_SHRN,
	TCTI_SIMD_ARITH_RSHRN,
	TCTI_SIMD_ARITH_SQSHRN,
	TCTI_SIMD_ARITH_UQSHRN,
	TCTI_SIMD_ARITH_SQRSHRN,
	TCTI_SIMD_ARITH_UQRSHRN,
	TCTI_SIMD_ARITH_SQSHRUN,
	TCTI_SIMD_ARITH_SQRSHRUN,
	TCTI_SIMD_ARITH_ABS,
	TCTI_SIMD_ARITH_NEG,
	TCTI_SIMD_ARITH_SQABS,
	TCTI_SIMD_ARITH_SQNEG,
	TCTI_SIMD_ARITH_CLS,
	TCTI_SIMD_ARITH_CLZ,
	TCTI_SIMD_ARITH_REV64,
	TCTI_SIMD_ARITH_REV32,
	TCTI_SIMD_ARITH_REV16,
	TCTI_SIMD_ARITH_CNT,
	TCTI_SIMD_ARITH_NOT,
	TCTI_SIMD_ARITH_RBIT,
	TCTI_SIMD_ARITH_FNEG,
	TCTI_SIMD_ARITH_SSHR,
	TCTI_SIMD_ARITH_USRA,
	TCTI_SIMD_ARITH_SSRA,
	TCTI_SIMD_ARITH_SRSHR,
	TCTI_SIMD_ARITH_URSHR,
	TCTI_SIMD_ARITH_SRSRA,
	TCTI_SIMD_ARITH_URSRA,
	TCTI_SIMD_ARITH_SHL,
	TCTI_SIMD_ARITH_SLI,
	TCTI_SIMD_ARITH_SRI,
	TCTI_SIMD_ARITH_SQSHLU,
	TCTI_SIMD_ARITH_SSHL,
	TCTI_SIMD_ARITH_USHL,
	TCTI_SIMD_ARITH_SQSHL,
	TCTI_SIMD_ARITH_UQSHL,
	TCTI_SIMD_ARITH_SRSHL,
	TCTI_SIMD_ARITH_URSHL,
	TCTI_SIMD_ARITH_SQRSHL,
	TCTI_SIMD_ARITH_UQRSHL,
	TCTI_SIMD_ARITH_USHR,
};

enum tcti_simd_vector_compare_op {
	TCTI_SIMD_COMPARE_CMEQ = 0,
	TCTI_SIMD_COMPARE_CMHI,
	TCTI_SIMD_COMPARE_CMTST,
	TCTI_SIMD_COMPARE_CMGT,
	TCTI_SIMD_COMPARE_CMGE,
	TCTI_SIMD_COMPARE_CMHS,
	TCTI_SIMD_COMPARE_CMLE,
	TCTI_SIMD_COMPARE_CMLT,
};

enum tcti_fp_scalar_move_op {
	TCTI_FP_MOVE_SIMD_TO_GPR = 0,
	TCTI_FP_MOVE_GPR_TO_SIMD,
	TCTI_FP_MOVE_REGISTER,
};

enum tcti_fp_scalar_1source_op {
	TCTI_FP1_FABS = 0,
	TCTI_FP1_FCVT,
	TCTI_FP1_FNEG,
};

enum tcti_fp_scalar_2source_op {
	TCTI_FP2_FDIV = 0,
	TCTI_FP2_FADD,
	TCTI_FP2_FSUB,
	TCTI_FP2_FMUL,
};

enum tcti_fp_int_convert_op {
	TCTI_FP_INT_SCVTF = 0,
	TCTI_FP_INT_UCVTF,
	TCTI_FP_INT_FCVTZS,
	TCTI_FP_INT_FCVTZU,
	TCTI_FP_INT_FCVTZU_FIXED,
	TCTI_FP_INT_FCVTZU_SIMD,
	TCTI_FP_INT_UCVTF_SIMD,
	TCTI_FP_INT_SCVTF_SIMD,
};

enum tcti_multiply_add_sub_op {
	TCTI_MUL_MADD = 0,
	TCTI_MUL_MSUB,
	TCTI_MUL_SMADDL,
	TCTI_MUL_SMSUBL,
	TCTI_MUL_SMULH,
	TCTI_MUL_UMADDL,
	TCTI_MUL_UMSUBL,
	TCTI_MUL_UMULH,
};

struct tcti_decoded_instruction {
	enum tcti_decode_class decode_class;
	u32 instruction;
	u8 rd;
	u8 rn;
	u8 rm;
	u8 ra;
	u8 rt;
	u8 rt2;
	u16 imm12;
	u16 imm16;
	u8 shift;
	u8 shift_amount;
	u8 halfword_shift;
	u8 access_size;
	u8 result_size;
	bool is_64bit;
	bool subtract;
	bool set_flags;
	bool immediate;
	s64 pc_relative_imm;
	bool page_relative;
	s64 branch_imm;
	bool link;
	u8 condition;
	u8 nzcv;
	bool nonzero;
	u8 test_bit;
	s64 memory_offset;
	bool load;
	bool simd_fp;
	bool simd_scalar;
	bool sign_extend_load;
	u8 offset_extend;
	bool offset_shift;
	bool invert_second_operand;
	u64 logical_immediate;
	enum tcti_memory_index_mode memory_index_mode;
	enum tcti_logical_op logical_op;
	enum tcti_simd_modified_immediate_op simd_modified_immediate_op;
	enum tcti_simd_vector_arithmetic_op simd_arithmetic_op;
	enum tcti_simd_vector_compare_op simd_compare_op;
	enum tcti_move_wide_op move_wide_op;
	enum tcti_branch_register_op branch_register_op;
	enum tcti_system_register system_register;
	enum tcti_conditional_select_op conditional_select_op;
	enum tcti_bitfield_op bitfield_op;
	enum tcti_data_processing_1source_op dp1_op;
	enum tcti_data_processing_2source_op dp2_op;
	enum tcti_fp_scalar_move_op fp_move_op;
	enum tcti_fp_scalar_1source_op fp1_op;
	enum tcti_fp_scalar_2source_op fp2_op;
	enum tcti_fp_int_convert_op fp_int_op;
	enum tcti_multiply_add_sub_op mul_op;
	enum tcti_simd_reduction_op simd_reduction_op;
	enum tcti_simd_element_move_op simd_element_move_op;
	bool system_register_write;
	u8 bitfield_immr;
	u8 bitfield_imms;
	u8 rs;
	u8 simd_destination_index;
	u8 simd_source_index;
	bool acquire;
	bool release;
	bool exclusive;
};

struct tcti_decoded_instruction tcti_decode_aarch64(u32 instruction);

#endif /* ORLIX_TCTI_DECODE_AARCH64_H */
