obj-y += engine.o
obj-y += report.o
obj-y += switch_debug.o
obj-y += decode_aarch64.o
obj-y += gadget_program.o
obj-y += block_cache.o
obj-y += tlb.o
obj-$(CONFIG_ORLIX_TCTI_KUNIT_TEST) += tests/tcti_decode_test.o
