obj-y += init.o
obj-y += delay.o
obj-y += uaccess.o
obj-y += fault.o
obj-y += mmap.o
obj-$(CONFIG_ORLIX_TCTI_HOSTED_EXEC) += orlix_tcti_user_page.o
obj-$(CONFIG_ORLIX_TCTI_HOSTED_EXEC) += orlix_tcti_invalidate.o
