obj-y += init.o
obj-y += delay.o
obj-y += uaccess.o
obj-y += fault.o
obj-y += mmap.o
obj-$(CONFIG_ORLIX_HOSTED_EXEC_TCTI) += tcti_user_page.o
obj-$(CONFIG_ORLIX_HOSTED_EXEC_TCTI) += tcti_invalidate.o
