#!/bin/bash
# Generate Linux ABI constants header from vendored Linux UAPI headers
# This extracts ONLY constant macro definitions, avoiding type conflicts

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

UAPI_ROOT="${PROJECT_ROOT}/third_party/linux-uapi/6.12/arm64/include"
OUTPUT_FILE="${PROJECT_ROOT}/include/ixland/linux_abi_constants.h"

echo "Generating Linux ABI constants from ${UAPI_ROOT}..."

GENERATION_DATE=$(date +"%Y-%m-%d %H:%M:%S")

cat > "${OUTPUT_FILE}" << EOFHEADER
/* IXLandSystem/include/ixland/linux_abi_constants.h
 *
 * AUTO-GENERATED from Linux UAPI headers. DO NOT EDIT BY HAND.
 *
 * This file is generated by scripts/generate_linux_constants.sh
 * from the vendored Linux UAPI headers (third_party/linux-uapi/6.12/arm64/include).
 *
 * Generation date: ${GENERATION_DATE}
 *
 * PURPOSE:
 * Linux UAPI headers define both constants AND types (sigset_t, struct flock)
 * that conflict with Darwin system headers. This file extracts ONLY the
 * constant macro definitions from Linux UAPI headers, allowing Linux-owner
 * code to use correct Linux ABI constants (O_CREAT=0x40, etc.) without
 * bringing in conflicting types.
 *
 * SOURCE OF TRUTH (Linux UAPI 6.12 arm64):
 *   - asm-generic/fcntl.h (O_*, F_*, AT_* constants)
 *   - linux/fcntl.h (AT_* constants)
 *   - asm-generic/ioctls.h (TIOC* constants)
 *   - asm-generic/signal.h (SIG*, _NSIG constants)
 *   - asm-generic/signal-defs.h (SIG_BLOCK, SIG_UNBLOCK, SIG_SETMASK)
 *   - asm-generic/poll.h (POLL* constants)
 *   - linux/eventpoll.h (EPOLL* constants)
 */

#ifndef IXLAND_LINUX_ABI_CONSTANTS_H
#define IXLAND_LINUX_ABI_CONSTANTS_H

EOFHEADER

# Extract O_* and F_* constants from asm-generic/fcntl.h
# Remove any trailing comments to avoid nested comment issues
grep -E '^#define\s+(O_|F_|FD_)[A-Z0-9_]+\s+[0-9x]' "${UAPI_ROOT}/asm-generic/fcntl.h" | \
  sed 's/[[:space:]]*\/\*.*$//' >> "${OUTPUT_FILE}" 2>/dev/null || true

# Add O_SYNC which has a different pattern
echo '#define __O_SYNC 04000000' >> "${OUTPUT_FILE}"
grep -E '^#define\s+O_SYNC\s+\(' "${UAPI_ROOT}/asm-generic/fcntl.h" | \
  sed 's/[[:space:]]*\/\*.*$//' >> "${OUTPUT_FILE}" 2>/dev/null || true

cat >> "${OUTPUT_FILE}" << 'EOFFCNTL'

/* ============================================================================
 * AT_* CONSTANTS - from Linux UAPI linux/fcntl.h
 * ============================================================================
 */

EOFFCNTL

# Extract AT_* constants from linux/fcntl.h
grep -E '^#define\s+AT_[A-Z0-9_]+\s+[-0-9x]' "${UAPI_ROOT}/linux/fcntl.h" | \
  sed 's/[[:space:]]*\/\*.*$//' >> "${OUTPUT_FILE}" 2>/dev/null || true

cat >> "${OUTPUT_FILE}" << 'EOFIOCTL'

/* ============================================================================
 * TERMINAL IOCTL CONSTANTS - from Linux UAPI asm-generic/ioctls.h
 * ============================================================================
 */

EOFIOCTL

# Extract TIOC*, TC*, FIO* constants from asm-generic/ioctls.h
grep -E '^#define\s+(TIOC|TC|FIO)[A-Z0-9_]*\s+0x[0-9a-fA-F]+' "${UAPI_ROOT}/asm-generic/ioctls.h" | \
  sed 's/[[:space:]]*\/\*.*$//' >> "${OUTPUT_FILE}" 2>/dev/null || true

cat >> "${OUTPUT_FILE}" << 'EOFSIG'

/* ============================================================================
 * SIGNAL CONSTANTS - from Linux UAPI asm-generic/signal.h
 * ============================================================================
 */

EOFSIG

# Extract _NSIG, SIG* constants from asm-generic/signal.h
grep -E '^#define\s+(_NSIG|SIG)[A-Z0-9_]*\s+[0-9]' "${UAPI_ROOT}/asm-generic/signal.h" | \
  head -40 | sed 's/[[:space:]]*\/\*.*$//' >> "${OUTPUT_FILE}" 2>/dev/null || true

cat >> "${OUTPUT_FILE}" << 'EOFSIGDEFS'

/* ============================================================================
 * SIGNAL MASK OPERATIONS - from Linux UAPI asm-generic/signal-defs.h
 * ============================================================================
 */

EOFSIGDEFS

# Extract SIG_BLOCK, SIG_UNBLOCK, SIG_SETMASK from asm-generic/signal-defs.h
grep -E '^#define\s+SIG_(BLOCK|UNBLOCK|SETMASK)\s+[0-9]' "${UAPI_ROOT}/asm-generic/signal-defs.h" >> "${OUTPUT_FILE}" 2>/dev/null || true

cat >> "${OUTPUT_FILE}" << 'EOFPOLL'

/* ============================================================================
 * POLL CONSTANTS - from Linux UAPI asm-generic/poll.h
 * ============================================================================
 */

EOFPOLL

# Extract POLL* constants from asm-generic/poll.h
grep -E '^#define\s+POLL[A-Z0-9_]*\s+0x[0-9a-fA-F]+' "${UAPI_ROOT}/asm-generic/poll.h" | \
  sed 's/[[:space:]]*\/\*.*$//' >> "${OUTPUT_FILE}" 2>/dev/null || true

cat >> "${OUTPUT_FILE}" << 'EOFEPOLL'

/* ============================================================================
 * EPOLL CONSTANTS - from Linux UAPI linux/eventpoll.h
 * ============================================================================
 */

EOFEPOLL

# Extract EPOLL* constants from linux/eventpoll.h
grep -E '^#define\s+EPOLL[A-Z0-9_]*\s+[0-9x]' "${UAPI_ROOT}/linux/eventpoll.h" | \
  sed 's/[[:space:]]*\/\*.*$//' >> "${OUTPUT_FILE}" 2>/dev/null || true

cat >> "${OUTPUT_FILE}" << 'EOFCLOCK'

/* ============================================================================
 * CLOCK CONSTANTS - from Linux UAPI linux/time.h
 * ============================================================================
 */

EOFCLOCK

# Extract CLOCK_* constants from linux/time.h
grep -E '^#define\s+CLOCK_[A-Z_]+\s+[0-9]' "${UAPI_ROOT}/linux/time.h" | \
  sed 's/[[:space:]]*\/\*.*$//' >> "${OUTPUT_FILE}" 2>/dev/null || true

cat >> "${OUTPUT_FILE}" << 'EOFFOOTER'

#endif /* IXLAND_LINUX_ABI_CONSTANTS_H */
EOFFOOTER

echo "Generated ${OUTPUT_FILE}"

# Verify the output
CONSTANT_COUNT=$(grep -c '^#define' "${OUTPUT_FILE}" || echo "0")
echo "Total constants extracted: ${CONSTANT_COUNT}"
