/* SPDX-License-Identifier: GPL-2.0-only */
#ifndef ORLIX_TCTI_TARGET_FEATURE_FIELD_DOMAIN_BINDING_ARTIFACT_GENERATOR_H
#define ORLIX_TCTI_TARGET_FEATURE_FIELD_DOMAIN_BINDING_ARTIFACT_GENERATOR_H

#include <stddef.h>
#include <stdio.h>

#include "target_feature_field_domain_binding.h"

#define ORLIX_TCTI_FEATURE_FIELD_DOMAIN_BINDING_EXPECTED_OCCURRENCES 605U
#define ORLIX_TCTI_FEATURE_FIELD_DOMAIN_BINDING_EXPECTED_IDENTITY_GROUPS 362U
#define ORLIX_TCTI_FEATURE_FIELD_DOMAIN_BINDING_EXPECTED_MAPPED 605U
#define ORLIX_TCTI_FEATURE_FIELD_DOMAIN_BINDING_EXPECTED_AMBIGUOUS_FIELD 0U
#define ORLIX_TCTI_FEATURE_FIELD_DOMAIN_BINDING_EXPECTED_ALTERNATIVES 606U

enum orlix_tcti_feature_field_domain_binding_artifact_error {
	ORLIX_TCTI_FEATURE_FIELD_DOMAIN_BINDING_ARTIFACT_OK,
	ORLIX_TCTI_FEATURE_FIELD_DOMAIN_BINDING_ARTIFACT_INVALID_ARGUMENT,
	ORLIX_TCTI_FEATURE_FIELD_DOMAIN_BINDING_ARTIFACT_FEATURE_IMPORT,
	ORLIX_TCTI_FEATURE_FIELD_DOMAIN_BINDING_ARTIFACT_REGISTER_IMPORT,
	ORLIX_TCTI_FEATURE_FIELD_DOMAIN_BINDING_ARTIFACT_BINDING,
	ORLIX_TCTI_FEATURE_FIELD_DOMAIN_BINDING_ARTIFACT_INVALID_BINDING,
	ORLIX_TCTI_FEATURE_FIELD_DOMAIN_BINDING_ARTIFACT_SOURCE_SPAN,
	ORLIX_TCTI_FEATURE_FIELD_DOMAIN_BINDING_ARTIFACT_COUNT_MISMATCH,
	ORLIX_TCTI_FEATURE_FIELD_DOMAIN_BINDING_ARTIFACT_IO,
};

/*
 * Serializes every Types.Field occurrence and matching declaration in source
 * order. V3 table rows retain the complete normalized semantic graph;
 * occurrence rows reference their declaration-alternative slices.
 */
enum orlix_tcti_feature_field_domain_binding_artifact_error
orlix_tcti_target_feature_field_domain_binding_artifact_validate(
	const struct orlix_tcti_feature_model *features,
	size_t feature_source_length,
	const struct orlix_tcti_register_model *registers,
	size_t register_source_length,
	const struct orlix_tcti_feature_field_domain_bindings *bindings);

enum orlix_tcti_feature_field_domain_binding_artifact_error
orlix_tcti_target_feature_field_domain_binding_artifact_emit_model(
	const struct orlix_tcti_feature_model *features,
	size_t feature_source_length,
	const struct orlix_tcti_register_model *registers,
	size_t register_source_length, FILE *output);

enum orlix_tcti_feature_field_domain_binding_artifact_error
orlix_tcti_target_feature_field_domain_binding_artifact_emit(
	const char *feature_source, size_t feature_length,
	const char *register_source, size_t register_length, FILE *output);

const char *orlix_tcti_target_feature_field_domain_binding_artifact_error_name(
	enum orlix_tcti_feature_field_domain_binding_artifact_error error);

#endif
