/* SPDX-License-Identifier: GPL-2.0-only */
#ifndef ORLIX_TCTI_DECODE_AARCH64_H
#define ORLIX_TCTI_DECODE_AARCH64_H

#include <linux/types.h>

#include "sve_decode.h"

enum orlix_tcti_decode_class {
	ORLIX_TCTI_DECODE_UNSUPPORTED = 0,
	ORLIX_TCTI_DECODE_SVC,
	ORLIX_TCTI_DECODE_BRK,
	ORLIX_TCTI_DECODE_HLT,
	ORLIX_TCTI_DECODE_HINT,
	ORLIX_TCTI_DECODE_BARRIER,
	ORLIX_TCTI_DECODE_CACHE_MAINTENANCE,
	ORLIX_TCTI_DECODE_MIN_MAX_IMMEDIATE,
	ORLIX_TCTI_DECODE_ADD_SUB_IMMEDIATE,
	ORLIX_TCTI_DECODE_ADD_SUB_SHIFTED_REGISTER,
	ORLIX_TCTI_DECODE_ADD_SUB_EXTENDED_REGISTER,
	ORLIX_TCTI_DECODE_ADD_SUB_WITH_CARRY,
	ORLIX_TCTI_DECODE_PC_RELATIVE_ADDRESS,
	ORLIX_TCTI_DECODE_UNCONDITIONAL_BRANCH_IMMEDIATE,
	ORLIX_TCTI_DECODE_UNCONDITIONAL_BRANCH_REGISTER,
	ORLIX_TCTI_DECODE_COMPARE_BRANCH_IMMEDIATE,
	ORLIX_TCTI_DECODE_COMPARE_BRANCH_EXTENSION,
	ORLIX_TCTI_DECODE_TEST_BRANCH_IMMEDIATE,
	ORLIX_TCTI_DECODE_CONDITIONAL_BRANCH_IMMEDIATE,
	ORLIX_TCTI_DECODE_CONDITIONAL_COMPARE,
	ORLIX_TCTI_DECODE_CONDITIONAL_SELECT,
	ORLIX_TCTI_DECODE_LOAD_LITERAL,
	ORLIX_TCTI_DECODE_LOAD_STORE_PAIR,
	ORLIX_TCTI_DECODE_LOAD_STORE_UNSIGNED_IMMEDIATE,
	ORLIX_TCTI_DECODE_LOAD_STORE_SIGNED_IMMEDIATE,
	ORLIX_TCTI_DECODE_LOAD_STORE_REGISTER_OFFSET,
	ORLIX_TCTI_DECODE_LOGICAL_SHIFTED_REGISTER,
	ORLIX_TCTI_DECODE_LOGICAL_IMMEDIATE,
	ORLIX_TCTI_DECODE_BITFIELD,
	ORLIX_TCTI_DECODE_EXTRACT,
	ORLIX_TCTI_DECODE_DATA_PROCESSING_1SOURCE,
	ORLIX_TCTI_DECODE_DATA_PROCESSING_2SOURCE,
	ORLIX_TCTI_DECODE_MULTIPLY_ADD_SUB,
	ORLIX_TCTI_DECODE_MOVE_WIDE_IMMEDIATE,
	ORLIX_TCTI_DECODE_SYSTEM_REGISTER,
	ORLIX_TCTI_DECODE_SME_PSTATE_IMMEDIATE,
	ORLIX_TCTI_DECODE_SVE_PREDICATED_INTEGER_BINARY,
	ORLIX_TCTI_DECODE_EXCLUSIVE_MONITOR_CLEAR,
	ORLIX_TCTI_DECODE_LOAD_STORE_EXCLUSIVE,
	ORLIX_TCTI_DECODE_LSE_ATOMIC,
	ORLIX_TCTI_DECODE_SIMD_MODIFIED_IMMEDIATE,
	ORLIX_TCTI_DECODE_SIMD_VECTOR_ELEMENT_MOVE,
	ORLIX_TCTI_DECODE_SIMD_TABLE_LOOKUP,
	ORLIX_TCTI_DECODE_SIMD_VECTOR_LOGICAL,
	ORLIX_TCTI_DECODE_SIMD_VECTOR_ARITHMETIC,
	ORLIX_TCTI_DECODE_SIMD_VECTOR_COMPARE,
	ORLIX_TCTI_DECODE_SIMD_VECTOR_REDUCTION,
	ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_SINGLE_STRUCTURE,
	ORLIX_TCTI_DECODE_SIMD_LOAD_REPLICATE,
	ORLIX_TCTI_DECODE_SIMD_LOAD_STORE_MULTIPLE_STRUCTURE,
	ORLIX_TCTI_DECODE_FP_SCALAR_IMMEDIATE,
	ORLIX_TCTI_DECODE_FP_SCALAR_MOVE,
	ORLIX_TCTI_DECODE_FP_SCALAR_1SOURCE,
	ORLIX_TCTI_DECODE_FP_SCALAR_2SOURCE,
	ORLIX_TCTI_DECODE_FP_SCALAR_3SOURCE,
	ORLIX_TCTI_DECODE_FP_SCALAR_COMPARE,
	ORLIX_TCTI_DECODE_FP_CONDITIONAL_SELECT,
	ORLIX_TCTI_DECODE_FP_INT_CONVERT,
};

enum orlix_tcti_memory_index_mode {
	ORLIX_TCTI_MEMORY_INDEX_SIGNED_OFFSET = 0,
	ORLIX_TCTI_MEMORY_INDEX_PRE,
	ORLIX_TCTI_MEMORY_INDEX_POST,
};

enum orlix_tcti_logical_op {
	ORLIX_TCTI_LOGICAL_AND = 0,
	ORLIX_TCTI_LOGICAL_BIC,
	ORLIX_TCTI_LOGICAL_ORR,
	ORLIX_TCTI_LOGICAL_ORN,
	ORLIX_TCTI_LOGICAL_EOR,
	ORLIX_TCTI_LOGICAL_BSL,
	ORLIX_TCTI_LOGICAL_BIT,
	ORLIX_TCTI_LOGICAL_BIF,
};

enum orlix_tcti_simd_modified_immediate_op {
	ORLIX_TCTI_SIMD_MODIMM_MOVI = 0,
	ORLIX_TCTI_SIMD_MODIMM_MVNI,
	ORLIX_TCTI_SIMD_MODIMM_ORR,
	ORLIX_TCTI_SIMD_MODIMM_BIC,
};

enum orlix_tcti_simd_reduction_op {
	ORLIX_TCTI_SIMD_REDUCTION_UMAXV = 0,
	ORLIX_TCTI_SIMD_REDUCTION_UMINV,
	ORLIX_TCTI_SIMD_REDUCTION_SMAXV,
	ORLIX_TCTI_SIMD_REDUCTION_SMINV,
	ORLIX_TCTI_SIMD_REDUCTION_ADDV,
	ORLIX_TCTI_SIMD_REDUCTION_SADDLV,
	ORLIX_TCTI_SIMD_REDUCTION_UADDLV,
	ORLIX_TCTI_SIMD_REDUCTION_ADDP,
	ORLIX_TCTI_SIMD_REDUCTION_FADDP,
	ORLIX_TCTI_SIMD_REDUCTION_FMAXNMP,
	ORLIX_TCTI_SIMD_REDUCTION_FMAXP,
	ORLIX_TCTI_SIMD_REDUCTION_FMINNMP,
	ORLIX_TCTI_SIMD_REDUCTION_FMINP,
	ORLIX_TCTI_SIMD_REDUCTION_FMAXNMV,
	ORLIX_TCTI_SIMD_REDUCTION_FMAXV,
	ORLIX_TCTI_SIMD_REDUCTION_FMINNMV,
	ORLIX_TCTI_SIMD_REDUCTION_FMINV,
};

enum orlix_tcti_simd_element_move_op {
	ORLIX_TCTI_SIMD_ELEMENT_MOVE_DUP = 0,
	ORLIX_TCTI_SIMD_ELEMENT_MOVE_XTN,
	ORLIX_TCTI_SIMD_ELEMENT_MOVE_UZP1,
	ORLIX_TCTI_SIMD_ELEMENT_MOVE_UZP2,
	ORLIX_TCTI_SIMD_ELEMENT_MOVE_TRN1,
	ORLIX_TCTI_SIMD_ELEMENT_MOVE_TRN2,
	ORLIX_TCTI_SIMD_ELEMENT_MOVE_ZIP1,
	ORLIX_TCTI_SIMD_ELEMENT_MOVE_ZIP2,
	ORLIX_TCTI_SIMD_ELEMENT_MOVE_UMOV,
	ORLIX_TCTI_SIMD_ELEMENT_MOVE_SMOV,
	ORLIX_TCTI_SIMD_ELEMENT_MOVE_INS_GPR,
	ORLIX_TCTI_SIMD_ELEMENT_MOVE_INS_ELEMENT,
	ORLIX_TCTI_SIMD_ELEMENT_MOVE_SSHLL,
	ORLIX_TCTI_SIMD_ELEMENT_MOVE_USHLL,
	ORLIX_TCTI_SIMD_ELEMENT_MOVE_EXT,
};

enum orlix_tcti_simd_table_lookup_op {
	ORLIX_TCTI_SIMD_TABLE_LOOKUP_TBL = 0,
	ORLIX_TCTI_SIMD_TABLE_LOOKUP_TBX,
};

enum orlix_tcti_move_wide_op {
	ORLIX_TCTI_MOVE_WIDE_MOVN = 0,
	ORLIX_TCTI_MOVE_WIDE_MOVZ,
	ORLIX_TCTI_MOVE_WIDE_MOVK,
};

enum orlix_tcti_branch_register_op {
	ORLIX_TCTI_BRANCH_REGISTER_BR = 0,
	ORLIX_TCTI_BRANCH_REGISTER_BLR,
	ORLIX_TCTI_BRANCH_REGISTER_RET,
};

enum orlix_tcti_compare_branch_condition {
	ORLIX_TCTI_COMPARE_BRANCH_GT = 0,
	ORLIX_TCTI_COMPARE_BRANCH_GE,
	ORLIX_TCTI_COMPARE_BRANCH_HI,
	ORLIX_TCTI_COMPARE_BRANCH_HS,
	ORLIX_TCTI_COMPARE_BRANCH_EQ,
	ORLIX_TCTI_COMPARE_BRANCH_NE,
	ORLIX_TCTI_COMPARE_BRANCH_LT,
	ORLIX_TCTI_COMPARE_BRANCH_LO,
};

struct orlix_tcti_system_accessor_semantic_key {
	u64 condition_identity;
	u64 access_identity;
};

enum orlix_tcti_sme_pstate_operation {
	ORLIX_TCTI_SME_PSTATE_SMSTART = 0,
	ORLIX_TCTI_SME_PSTATE_SMSTOP,
};

enum orlix_tcti_barrier_op {
	ORLIX_TCTI_BARRIER_DSB = 0,
	ORLIX_TCTI_BARRIER_DMB,
	ORLIX_TCTI_BARRIER_ISB,
};

enum orlix_tcti_cache_maintenance_op {
	ORLIX_TCTI_CACHE_IC_IVAU = 0,
	ORLIX_TCTI_CACHE_DC_CVAC,
	ORLIX_TCTI_CACHE_DC_CVAU,
	ORLIX_TCTI_CACHE_DC_CIVAC,
};

enum orlix_tcti_conditional_select_op {
	ORLIX_TCTI_CONDITIONAL_SELECT_CSEL = 0,
	ORLIX_TCTI_CONDITIONAL_SELECT_CSINC,
	ORLIX_TCTI_CONDITIONAL_SELECT_CSINV,
	ORLIX_TCTI_CONDITIONAL_SELECT_CSNEG,
};

enum orlix_tcti_bitfield_op {
	ORLIX_TCTI_BITFIELD_SBFM = 0,
	ORLIX_TCTI_BITFIELD_BFM,
	ORLIX_TCTI_BITFIELD_UBFM,
};

enum orlix_tcti_data_processing_2source_op {
	ORLIX_TCTI_DP2_UDIV = 0,
	ORLIX_TCTI_DP2_SDIV,
	ORLIX_TCTI_DP2_LSLV,
	ORLIX_TCTI_DP2_LSRV,
	ORLIX_TCTI_DP2_ASRV,
	ORLIX_TCTI_DP2_RORV,
	ORLIX_TCTI_DP2_CRC32,
	ORLIX_TCTI_DP2_CRC32C,
	ORLIX_TCTI_DP2_SMAX,
	ORLIX_TCTI_DP2_UMAX,
	ORLIX_TCTI_DP2_SMIN,
	ORLIX_TCTI_DP2_UMIN,
};

enum orlix_tcti_lse_atomic_op {
	ORLIX_TCTI_LSE_ATOMIC_CAS = 0,
	ORLIX_TCTI_LSE_ATOMIC_SWP,
	ORLIX_TCTI_LSE_ATOMIC_ADD,
	ORLIX_TCTI_LSE_ATOMIC_CLR,
	ORLIX_TCTI_LSE_ATOMIC_EOR,
	ORLIX_TCTI_LSE_ATOMIC_SET,
	ORLIX_TCTI_LSE_ATOMIC_SMAX,
	ORLIX_TCTI_LSE_ATOMIC_SMIN,
	ORLIX_TCTI_LSE_ATOMIC_UMAX,
	ORLIX_TCTI_LSE_ATOMIC_UMIN,
};

enum orlix_tcti_data_processing_1source_op {
	ORLIX_TCTI_DP1_CLZ = 0,
	ORLIX_TCTI_DP1_RBIT,
	ORLIX_TCTI_DP1_REV,
	ORLIX_TCTI_DP1_REV16,
	ORLIX_TCTI_DP1_REV32,
	ORLIX_TCTI_DP1_CLS,
	ORLIX_TCTI_DP1_CTZ,
	ORLIX_TCTI_DP1_CNT,
	ORLIX_TCTI_DP1_ABS,
};

enum orlix_tcti_simd_vector_arithmetic_op {
	ORLIX_TCTI_SIMD_ARITH_ADD = 0,
	ORLIX_TCTI_SIMD_ARITH_SUB,
	ORLIX_TCTI_SIMD_ARITH_SHADD,
	ORLIX_TCTI_SIMD_ARITH_UHADD,
	ORLIX_TCTI_SIMD_ARITH_SRHADD,
	ORLIX_TCTI_SIMD_ARITH_URHADD,
	ORLIX_TCTI_SIMD_ARITH_SHSUB,
	ORLIX_TCTI_SIMD_ARITH_UHSUB,
	ORLIX_TCTI_SIMD_ARITH_ADDP,
	ORLIX_TCTI_SIMD_ARITH_SADDLP,
	ORLIX_TCTI_SIMD_ARITH_UADDLP,
	ORLIX_TCTI_SIMD_ARITH_SADALP,
	ORLIX_TCTI_SIMD_ARITH_UADALP,
	ORLIX_TCTI_SIMD_ARITH_SADDW,
	ORLIX_TCTI_SIMD_ARITH_UADDW,
	ORLIX_TCTI_SIMD_ARITH_SSUBW,
	ORLIX_TCTI_SIMD_ARITH_USUBW,
	ORLIX_TCTI_SIMD_ARITH_SADDL,
	ORLIX_TCTI_SIMD_ARITH_UADDL,
	ORLIX_TCTI_SIMD_ARITH_SSUBL,
	ORLIX_TCTI_SIMD_ARITH_USUBL,
	ORLIX_TCTI_SIMD_ARITH_SMAXP,
	ORLIX_TCTI_SIMD_ARITH_UMAXP,
	ORLIX_TCTI_SIMD_ARITH_SMINP,
	ORLIX_TCTI_SIMD_ARITH_UMINP,
	ORLIX_TCTI_SIMD_ARITH_SQADD,
	ORLIX_TCTI_SIMD_ARITH_UQADD,
	ORLIX_TCTI_SIMD_ARITH_SQSUB,
	ORLIX_TCTI_SIMD_ARITH_UQSUB,
	ORLIX_TCTI_SIMD_ARITH_SQDMULH,
	ORLIX_TCTI_SIMD_ARITH_SQRDMULH,
	ORLIX_TCTI_SIMD_ARITH_MUL,
	ORLIX_TCTI_SIMD_ARITH_PMUL,
	ORLIX_TCTI_SIMD_ARITH_PMULL,
	ORLIX_TCTI_SIMD_ARITH_SMULL,
	ORLIX_TCTI_SIMD_ARITH_UMULL,
	ORLIX_TCTI_SIMD_ARITH_SMLAL,
	ORLIX_TCTI_SIMD_ARITH_UMLAL,
	ORLIX_TCTI_SIMD_ARITH_SMLSL,
	ORLIX_TCTI_SIMD_ARITH_UMLSL,
	ORLIX_TCTI_SIMD_ARITH_SQDMULL,
	ORLIX_TCTI_SIMD_ARITH_SQDMLAL,
	ORLIX_TCTI_SIMD_ARITH_SQDMLSL,
	ORLIX_TCTI_SIMD_ARITH_AESE,
	ORLIX_TCTI_SIMD_ARITH_AESD,
	ORLIX_TCTI_SIMD_ARITH_AESMC,
	ORLIX_TCTI_SIMD_ARITH_AESIMC,
	ORLIX_TCTI_SIMD_ARITH_SHA1C,
	ORLIX_TCTI_SIMD_ARITH_SHA1P,
	ORLIX_TCTI_SIMD_ARITH_SHA1M,
	ORLIX_TCTI_SIMD_ARITH_SHA1SU0,
	ORLIX_TCTI_SIMD_ARITH_SHA1H,
	ORLIX_TCTI_SIMD_ARITH_SHA1SU1,
	ORLIX_TCTI_SIMD_ARITH_SHA256H,
	ORLIX_TCTI_SIMD_ARITH_SHA256H2,
	ORLIX_TCTI_SIMD_ARITH_SHA256SU1,
	ORLIX_TCTI_SIMD_ARITH_SHA256SU0,
	ORLIX_TCTI_SIMD_ARITH_SHA512H,
	ORLIX_TCTI_SIMD_ARITH_SHA512H2,
	ORLIX_TCTI_SIMD_ARITH_SHA512SU1,
	ORLIX_TCTI_SIMD_ARITH_SHA512SU0,
	ORLIX_TCTI_SIMD_ARITH_EOR3,
	ORLIX_TCTI_SIMD_ARITH_RAX1,
	ORLIX_TCTI_SIMD_ARITH_XAR,
	ORLIX_TCTI_SIMD_ARITH_BCAX,
	ORLIX_TCTI_SIMD_ARITH_SM4E,
	ORLIX_TCTI_SIMD_ARITH_SM4EKEY,
	ORLIX_TCTI_SIMD_ARITH_SM3SS1,
	ORLIX_TCTI_SIMD_ARITH_SM3TT1A,
	ORLIX_TCTI_SIMD_ARITH_SM3TT1B,
	ORLIX_TCTI_SIMD_ARITH_SM3TT2A,
	ORLIX_TCTI_SIMD_ARITH_SM3TT2B,
	ORLIX_TCTI_SIMD_ARITH_SM3PARTW1,
	ORLIX_TCTI_SIMD_ARITH_SM3PARTW2,
	ORLIX_TCTI_SIMD_ARITH_MLA,
	ORLIX_TCTI_SIMD_ARITH_MLS,
	ORLIX_TCTI_SIMD_ARITH_SMAX,
	ORLIX_TCTI_SIMD_ARITH_UMAX,
	ORLIX_TCTI_SIMD_ARITH_SMIN,
	ORLIX_TCTI_SIMD_ARITH_UMIN,
	ORLIX_TCTI_SIMD_ARITH_SABD,
	ORLIX_TCTI_SIMD_ARITH_UABD,
	ORLIX_TCTI_SIMD_ARITH_SABA,
	ORLIX_TCTI_SIMD_ARITH_UABA,
	ORLIX_TCTI_SIMD_ARITH_SABDL,
	ORLIX_TCTI_SIMD_ARITH_UABDL,
	ORLIX_TCTI_SIMD_ARITH_SABAL,
	ORLIX_TCTI_SIMD_ARITH_UABAL,
	ORLIX_TCTI_SIMD_ARITH_ADDHN,
	ORLIX_TCTI_SIMD_ARITH_SUBHN,
	ORLIX_TCTI_SIMD_ARITH_RADDHN,
	ORLIX_TCTI_SIMD_ARITH_RSUBHN,
	ORLIX_TCTI_SIMD_ARITH_SQXTN,
	ORLIX_TCTI_SIMD_ARITH_UQXTN,
	ORLIX_TCTI_SIMD_ARITH_SQXTUN,
	ORLIX_TCTI_SIMD_ARITH_SHRN,
	ORLIX_TCTI_SIMD_ARITH_RSHRN,
	ORLIX_TCTI_SIMD_ARITH_SQSHRN,
	ORLIX_TCTI_SIMD_ARITH_UQSHRN,
	ORLIX_TCTI_SIMD_ARITH_SQRSHRN,
	ORLIX_TCTI_SIMD_ARITH_UQRSHRN,
	ORLIX_TCTI_SIMD_ARITH_SQSHRUN,
	ORLIX_TCTI_SIMD_ARITH_SQRSHRUN,
	ORLIX_TCTI_SIMD_ARITH_ABS,
	ORLIX_TCTI_SIMD_ARITH_NEG,
	ORLIX_TCTI_SIMD_ARITH_SQABS,
	ORLIX_TCTI_SIMD_ARITH_SQNEG,
	ORLIX_TCTI_SIMD_ARITH_CLS,
	ORLIX_TCTI_SIMD_ARITH_CLZ,
	ORLIX_TCTI_SIMD_ARITH_REV64,
	ORLIX_TCTI_SIMD_ARITH_REV32,
	ORLIX_TCTI_SIMD_ARITH_REV16,
	ORLIX_TCTI_SIMD_ARITH_CNT,
	ORLIX_TCTI_SIMD_ARITH_NOT,
	ORLIX_TCTI_SIMD_ARITH_RBIT,
	ORLIX_TCTI_SIMD_ARITH_FNEG,
	ORLIX_TCTI_SIMD_ARITH_SUQADD,
	ORLIX_TCTI_SIMD_ARITH_USQADD,
	ORLIX_TCTI_SIMD_ARITH_FABD,
	ORLIX_TCTI_SIMD_ARITH_FACGE,
	ORLIX_TCTI_SIMD_ARITH_FACGT,
	ORLIX_TCTI_SIMD_ARITH_FCMEQ,
	ORLIX_TCTI_SIMD_ARITH_FCMGE,
	ORLIX_TCTI_SIMD_ARITH_FCMGT,
	ORLIX_TCTI_SIMD_ARITH_FMULX,
	ORLIX_TCTI_SIMD_ARITH_FRECPS,
	ORLIX_TCTI_SIMD_ARITH_FRSQRTS,
	ORLIX_TCTI_SIMD_ARITH_FADDP,
	ORLIX_TCTI_SIMD_ARITH_FADD,
	ORLIX_TCTI_SIMD_ARITH_FDIV,
	ORLIX_TCTI_SIMD_ARITH_FMAXNMP,
	ORLIX_TCTI_SIMD_ARITH_FMAXNM,
	ORLIX_TCTI_SIMD_ARITH_FMAXP,
	ORLIX_TCTI_SIMD_ARITH_FMAX,
	ORLIX_TCTI_SIMD_ARITH_FMINNMP,
	ORLIX_TCTI_SIMD_ARITH_FMINNM,
	ORLIX_TCTI_SIMD_ARITH_FMINP,
	ORLIX_TCTI_SIMD_ARITH_FMIN,
	ORLIX_TCTI_SIMD_ARITH_FMLA,
	ORLIX_TCTI_SIMD_ARITH_FMLS,
	ORLIX_TCTI_SIMD_ARITH_FMUL,
	ORLIX_TCTI_SIMD_ARITH_FSUB,
	ORLIX_TCTI_SIMD_ARITH_SSHR,
	ORLIX_TCTI_SIMD_ARITH_USRA,
	ORLIX_TCTI_SIMD_ARITH_SSRA,
	ORLIX_TCTI_SIMD_ARITH_SRSHR,
	ORLIX_TCTI_SIMD_ARITH_URSHR,
	ORLIX_TCTI_SIMD_ARITH_SRSRA,
	ORLIX_TCTI_SIMD_ARITH_URSRA,
	ORLIX_TCTI_SIMD_ARITH_SHL,
	ORLIX_TCTI_SIMD_ARITH_SLI,
	ORLIX_TCTI_SIMD_ARITH_SRI,
	ORLIX_TCTI_SIMD_ARITH_SQSHLU,
	ORLIX_TCTI_SIMD_ARITH_SSHL,
	ORLIX_TCTI_SIMD_ARITH_USHL,
	ORLIX_TCTI_SIMD_ARITH_SQSHL,
	ORLIX_TCTI_SIMD_ARITH_UQSHL,
	ORLIX_TCTI_SIMD_ARITH_SRSHL,
	ORLIX_TCTI_SIMD_ARITH_URSHL,
	ORLIX_TCTI_SIMD_ARITH_SQRSHL,
	ORLIX_TCTI_SIMD_ARITH_UQRSHL,
	ORLIX_TCTI_SIMD_ARITH_USHR,
	ORLIX_TCTI_SIMD_ARITH_FRECPE,
	ORLIX_TCTI_SIMD_ARITH_FRECPX,
	ORLIX_TCTI_SIMD_ARITH_FRSQRTE,
	ORLIX_TCTI_SIMD_ARITH_FCVTXN,
	ORLIX_TCTI_SIMD_ARITH_FABS,
	ORLIX_TCTI_SIMD_ARITH_FSQRT,
	ORLIX_TCTI_SIMD_ARITH_FRINTN,
	ORLIX_TCTI_SIMD_ARITH_FRINTP,
	ORLIX_TCTI_SIMD_ARITH_FRINTM,
	ORLIX_TCTI_SIMD_ARITH_FRINTZ,
	ORLIX_TCTI_SIMD_ARITH_FRINTA,
	ORLIX_TCTI_SIMD_ARITH_FRINTX,
	ORLIX_TCTI_SIMD_ARITH_FRINTI,
	ORLIX_TCTI_SIMD_ARITH_FCMLE_ZERO,
	ORLIX_TCTI_SIMD_ARITH_FCMLT_ZERO,
	ORLIX_TCTI_SIMD_ARITH_FCMEQ_ZERO,
	ORLIX_TCTI_SIMD_ARITH_FCMGE_ZERO,
	ORLIX_TCTI_SIMD_ARITH_FCMGT_ZERO,
	ORLIX_TCTI_SIMD_ARITH_FCVTN,
	ORLIX_TCTI_SIMD_ARITH_FCVTL,
	ORLIX_TCTI_SIMD_ARITH_URECPE,
	ORLIX_TCTI_SIMD_ARITH_URSQRTE,
};

enum orlix_tcti_simd_vector_compare_op {
	ORLIX_TCTI_SIMD_COMPARE_CMEQ = 0,
	ORLIX_TCTI_SIMD_COMPARE_CMHI,
	ORLIX_TCTI_SIMD_COMPARE_CMTST,
	ORLIX_TCTI_SIMD_COMPARE_CMGT,
	ORLIX_TCTI_SIMD_COMPARE_CMGE,
	ORLIX_TCTI_SIMD_COMPARE_CMHS,
	ORLIX_TCTI_SIMD_COMPARE_CMLE,
	ORLIX_TCTI_SIMD_COMPARE_CMLT,
};

enum orlix_tcti_fp_scalar_move_op {
	ORLIX_TCTI_FP_MOVE_SIMD_TO_GPR = 0,
	ORLIX_TCTI_FP_MOVE_GPR_TO_SIMD,
	ORLIX_TCTI_FP_MOVE_SIMD_HIGH_TO_GPR,
	ORLIX_TCTI_FP_MOVE_GPR_TO_SIMD_HIGH,
	ORLIX_TCTI_FP_MOVE_REGISTER,
};

enum orlix_tcti_fp_scalar_1source_op {
	ORLIX_TCTI_FP1_FABS = 0,
	ORLIX_TCTI_FP1_FCVT,
	ORLIX_TCTI_FP1_FNEG,
	ORLIX_TCTI_FP1_FSQRT,
	ORLIX_TCTI_FP1_FRINTN,
	ORLIX_TCTI_FP1_FRINTP,
	ORLIX_TCTI_FP1_FRINTM,
	ORLIX_TCTI_FP1_FRINTZ,
	ORLIX_TCTI_FP1_FRINTA,
	ORLIX_TCTI_FP1_FRINTX,
	ORLIX_TCTI_FP1_FRINTI,
};

enum orlix_tcti_fp_scalar_2source_op {
	ORLIX_TCTI_FP2_FDIV = 0,
	ORLIX_TCTI_FP2_FADD,
	ORLIX_TCTI_FP2_FSUB,
	ORLIX_TCTI_FP2_FMUL,
	ORLIX_TCTI_FP2_FMAX,
	ORLIX_TCTI_FP2_FMIN,
	ORLIX_TCTI_FP2_FMAXNM,
	ORLIX_TCTI_FP2_FMINNM,
	ORLIX_TCTI_FP2_FNMUL,
};

enum orlix_tcti_fp_scalar_3source_op {
	ORLIX_TCTI_FP3_FMADD = 0,
	ORLIX_TCTI_FP3_FMSUB,
	ORLIX_TCTI_FP3_FNMADD,
	ORLIX_TCTI_FP3_FNMSUB,
};

enum orlix_tcti_fp_int_convert_op {
	ORLIX_TCTI_FP_INT_SCVTF = 0,
	ORLIX_TCTI_FP_INT_UCVTF,
	ORLIX_TCTI_FP_INT_FCVTZS,
	ORLIX_TCTI_FP_INT_FCVTZU,
	ORLIX_TCTI_FP_INT_FCVTNS,
	ORLIX_TCTI_FP_INT_FCVTNU,
	ORLIX_TCTI_FP_INT_FCVTPS,
	ORLIX_TCTI_FP_INT_FCVTPU,
	ORLIX_TCTI_FP_INT_FCVTMS,
	ORLIX_TCTI_FP_INT_FCVTMU,
	ORLIX_TCTI_FP_INT_FCVTAS,
	ORLIX_TCTI_FP_INT_FCVTAU,
	ORLIX_TCTI_FP_INT_FCVTZS_FIXED,
	ORLIX_TCTI_FP_INT_FCVTZU_FIXED,
	ORLIX_TCTI_FP_INT_SCVTF_FIXED,
	ORLIX_TCTI_FP_INT_UCVTF_FIXED,
	ORLIX_TCTI_FP_INT_FCVTZS_FIXED_SIMD,
	ORLIX_TCTI_FP_INT_FCVTZU_FIXED_SIMD,
	ORLIX_TCTI_FP_INT_SCVTF_FIXED_SIMD,
	ORLIX_TCTI_FP_INT_UCVTF_FIXED_SIMD,
	ORLIX_TCTI_FP_INT_FCVTNS_SIMD,
	ORLIX_TCTI_FP_INT_FCVTNU_SIMD,
	ORLIX_TCTI_FP_INT_FCVTPS_SIMD,
	ORLIX_TCTI_FP_INT_FCVTPU_SIMD,
	ORLIX_TCTI_FP_INT_FCVTMS_SIMD,
	ORLIX_TCTI_FP_INT_FCVTMU_SIMD,
	ORLIX_TCTI_FP_INT_FCVTZS_SIMD,
	ORLIX_TCTI_FP_INT_FCVTZU_SIMD,
	ORLIX_TCTI_FP_INT_FCVTAS_SIMD,
	ORLIX_TCTI_FP_INT_FCVTAU_SIMD,
	ORLIX_TCTI_FP_INT_UCVTF_SIMD,
	ORLIX_TCTI_FP_INT_SCVTF_SIMD,
};

enum orlix_tcti_multiply_add_sub_op {
	ORLIX_TCTI_MUL_MADD = 0,
	ORLIX_TCTI_MUL_MSUB,
	ORLIX_TCTI_MUL_SMADDL,
	ORLIX_TCTI_MUL_SMSUBL,
	ORLIX_TCTI_MUL_SMULH,
	ORLIX_TCTI_MUL_UMADDL,
	ORLIX_TCTI_MUL_UMSUBL,
	ORLIX_TCTI_MUL_UMULH,
};

enum orlix_tcti_min_max_immediate_op {
	ORLIX_TCTI_MIN_MAX_IMMEDIATE_SMAX = 0,
	ORLIX_TCTI_MIN_MAX_IMMEDIATE_UMAX,
	ORLIX_TCTI_MIN_MAX_IMMEDIATE_SMIN,
	ORLIX_TCTI_MIN_MAX_IMMEDIATE_UMIN,
};

struct orlix_tcti_decoded_instruction {
	enum orlix_tcti_decode_class decode_class;
	u32 instruction;
	u8 rd;
	u8 rn;
	u8 rm;
	u8 ra;
	u8 rt;
	u8 rt2;
	u16 system_accessor_selector;
	u32 system_accessor_id;
	u32 system_accessor_condition;
	u32 system_accessor_access;
	u8 system_accessor_disposition;
	u8 system_accessor_implementation;
	u64 system_accessor_selector_identity;
	u64 system_accessor_condition_identity;
	u64 system_accessor_access_identity;
	/* Source-derived canonical identity for aliases sharing one encoding. */
	struct orlix_tcti_system_accessor_semantic_key system_accessor_semantic_key;
	const char *system_accessor_decoder_owner;
	const char *system_accessor_execution_owner;
	u16 imm12;
	u16 imm16;
	u8 min_max_immediate;
	u8 hint_imm;
	u8 barrier_option;
	u8 shift;
	u8 shift_amount;
	u8 halfword_shift;
	u8 access_size;
	u8 result_size;
	bool is_64bit;
	bool subtract;
	bool set_flags;
	bool immediate;
	bool fp_conditional;
	bool fp_signal_all_nans;
	bool barrier_nxs;
	s64 pc_relative_imm;
	bool page_relative;
	s64 branch_imm;
	bool link;
	u8 condition;
	u8 nzcv;
	u8 imm6;
	bool nonzero;
	bool compare_branch_immediate;
	u8 compare_branch_access_size;
	enum orlix_tcti_compare_branch_condition compare_branch_condition;
	u8 test_bit;
	s64 memory_offset;
	bool load;
	bool simd_fp;
	bool simd_scalar;
	bool simd_q;
	bool simd_indexed;
	bool sign_extend_load;
	bool prefetch;
	u8 offset_extend;
	bool offset_shift;
	bool invert_second_operand;
	u64 logical_immediate;
	enum orlix_tcti_memory_index_mode memory_index_mode;
	enum orlix_tcti_logical_op logical_op;
	enum orlix_tcti_simd_modified_immediate_op simd_modified_immediate_op;
	enum orlix_tcti_simd_vector_arithmetic_op simd_arithmetic_op;
	enum orlix_tcti_simd_vector_compare_op simd_compare_op;
	enum orlix_tcti_move_wide_op move_wide_op;
	enum orlix_tcti_branch_register_op branch_register_op;
	enum orlix_tcti_sme_pstate_operation sme_pstate_operation;
	enum orlix_tcti_sve_integer_binary_op sve_integer_binary_op;
	enum orlix_tcti_sve_predication sve_predication;
	enum orlix_tcti_barrier_op barrier_op;
	enum orlix_tcti_cache_maintenance_op cache_maintenance_op;
	enum orlix_tcti_conditional_select_op conditional_select_op;
	enum orlix_tcti_bitfield_op bitfield_op;
	enum orlix_tcti_data_processing_1source_op dp1_op;
	enum orlix_tcti_data_processing_2source_op dp2_op;
	enum orlix_tcti_lse_atomic_op lse_atomic_op;
	enum orlix_tcti_fp_scalar_move_op fp_move_op;
	enum orlix_tcti_fp_scalar_1source_op fp1_op;
	enum orlix_tcti_fp_scalar_2source_op fp2_op;
	enum orlix_tcti_fp_scalar_3source_op fp3_op;
	enum orlix_tcti_fp_int_convert_op fp_int_op;
	enum orlix_tcti_multiply_add_sub_op mul_op;
	enum orlix_tcti_min_max_immediate_op min_max_immediate_op;
	enum orlix_tcti_simd_reduction_op simd_reduction_op;
	enum orlix_tcti_simd_element_move_op simd_element_move_op;
	enum orlix_tcti_simd_table_lookup_op simd_table_lookup_op;
	bool system_register_write;
	bool sme_streaming_mode;
	bool sme_za;
	u8 sve_pg;
	u8 sve_element_bytes;
	u8 bitfield_immr;
	u8 bitfield_imms;
	u8 rs;
	u8 simd_destination_index;
	u8 simd_source_index;
	u8 simd_table_count;
	u8 simd_structure_count;
	u8 simd_lane_index;
	bool simd_replicate;
	bool simd_interleaved;
	bool acquire;
	bool release;
	bool exclusive;
	bool pair;
	bool lse128;
};

struct orlix_tcti_decoded_instruction orlix_tcti_decode_aarch64(u32 instruction);

#endif /* ORLIX_TCTI_DECODE_AARCH64_H */
