/* IXLandSystem/include/ixland/linux_abi_constants.h
 *
 * AUTO-GENERATED from Linux UAPI headers. DO NOT EDIT BY HAND.
 *
 * This file is generated by scripts/generate_linux_constants.sh
 * from the vendored Linux UAPI headers (third_party/linux-uapi/6.12/arm64/include).
 *
 * Generation date: 2026-04-25 09:30:55
 *
 * PURPOSE:
 * Linux UAPI headers define both constants AND types (sigset_t, struct flock)
 * that conflict with Darwin system headers. This file extracts ONLY the
 * constant macro definitions from Linux UAPI headers, allowing Linux-owner
 * code to use correct Linux ABI constants (O_CREAT=0x40, etc.) without
 * bringing in conflicting types.
 *
 * SOURCE OF TRUTH (Linux UAPI 6.12 arm64):
 *   - asm-generic/fcntl.h (O_*, F_*, AT_* constants)
 *   - linux/fcntl.h (AT_* constants)
 *   - asm-generic/ioctls.h (TIOC* constants)
 *   - asm-generic/signal.h (SIG*, _NSIG constants)
 *   - asm-generic/signal-defs.h (SIG_BLOCK, SIG_UNBLOCK, SIG_SETMASK)
 *   - asm-generic/poll.h (POLL* constants)
 *   - linux/eventpoll.h (EPOLL* constants)
 */

#ifndef IXLAND_LINUX_ABI_CONSTANTS_H
#define IXLAND_LINUX_ABI_CONSTANTS_H

#define O_ACCMODE	00000003
#define O_RDONLY	00000000
#define O_WRONLY	00000001
#define O_RDWR		00000002
#define O_CREAT		00000100
#define O_EXCL		00000200
#define O_NOCTTY	00000400
#define O_TRUNC		00001000
#define O_APPEND	00002000
#define O_NONBLOCK	00004000
#define O_DSYNC		00010000
#define O_DIRECT	00040000
#define O_LARGEFILE	00100000
#define O_DIRECTORY	00200000
#define O_NOFOLLOW	00400000
#define O_NOATIME	01000000
#define O_CLOEXEC	02000000
#define O_PATH		010000000
#define F_DUPFD		0
#define F_GETFD		1
#define F_SETFD		2
#define F_GETFL		3
#define F_SETFL		4
#define F_GETLK		5
#define F_SETLK		6
#define F_SETLKW	7
#define F_SETOWN	8
#define F_GETOWN	9
#define F_SETSIG	10
#define F_GETSIG	11
#define F_GETLK64	12
#define F_SETLK64	13
#define F_SETLKW64	14
#define F_SETOWN_EX	15
#define F_GETOWN_EX	16
#define F_GETOWNER_UIDS	17
#define F_OFD_GETLK	36
#define F_OFD_SETLK	37
#define F_OFD_SETLKW	38
#define F_OWNER_TID	0
#define F_OWNER_PID	1
#define F_OWNER_PGRP	2
#define FD_CLOEXEC	1
#define F_RDLCK		0
#define F_WRLCK		1
#define F_UNLCK		2
#define F_EXLCK		4
#define F_SHLCK		8
#define F_LINUX_SPECIFIC_BASE	1024
#define __O_SYNC 04000000
#define O_SYNC		(__O_SYNC|O_DSYNC)

/* ============================================================================
 * AT_* CONSTANTS - from Linux UAPI linux/fcntl.h
 * ============================================================================
 */

#define AT_FDCWD		-100
#define AT_SYMLINK_NOFOLLOW		0x100
#define AT_SYMLINK_FOLLOW		0x400
#define AT_NO_AUTOMOUNT			0x800
#define AT_EMPTY_PATH			0x1000
#define AT_STATX_SYNC_TYPE		0x6000
#define AT_STATX_SYNC_AS_STAT		0x0000
#define AT_STATX_FORCE_SYNC		0x2000
#define AT_STATX_DONT_SYNC		0x4000
#define AT_RECURSIVE			0x8000
#define AT_RENAME_NOREPLACE	0x0001
#define AT_RENAME_EXCHANGE	0x0002
#define AT_RENAME_WHITEOUT	0x0004
#define AT_EACCESS		0x200
#define AT_REMOVEDIR		0x200
#define AT_HANDLE_FID		0x200
#define AT_HANDLE_MNT_ID_UNIQUE	0x001

/* ============================================================================
 * TERMINAL IOCTL CONSTANTS - from Linux UAPI asm-generic/ioctls.h
 * ============================================================================
 */

#define TCGETS		0x5401
#define TCSETS		0x5402
#define TCSETSW		0x5403
#define TCSETSF		0x5404
#define TCGETA		0x5405
#define TCSETA		0x5406
#define TCSETAW		0x5407
#define TCSETAF		0x5408
#define TCSBRK		0x5409
#define TCXONC		0x540A
#define TCFLSH		0x540B
#define TIOCEXCL	0x540C
#define TIOCNXCL	0x540D
#define TIOCSCTTY	0x540E
#define TIOCGPGRP	0x540F
#define TIOCSPGRP	0x5410
#define TIOCOUTQ	0x5411
#define TIOCSTI		0x5412
#define TIOCGWINSZ	0x5413
#define TIOCSWINSZ	0x5414
#define TIOCMGET	0x5415
#define TIOCMBIS	0x5416
#define TIOCMBIC	0x5417
#define TIOCMSET	0x5418
#define TIOCGSOFTCAR	0x5419
#define TIOCSSOFTCAR	0x541A
#define FIONREAD	0x541B
#define TIOCLINUX	0x541C
#define TIOCCONS	0x541D
#define TIOCGSERIAL	0x541E
#define TIOCSSERIAL	0x541F
#define TIOCPKT		0x5420
#define FIONBIO		0x5421
#define TIOCNOTTY	0x5422
#define TIOCSETD	0x5423
#define TIOCGETD	0x5424
#define TCSBRKP		0x5425
#define TIOCSBRK	0x5427
#define TIOCCBRK	0x5428
#define TIOCGSID	0x5429
#define TIOCGRS485	0x542E
#define TIOCSRS485	0x542F
#define TCGETX		0x5432
#define TCSETX		0x5433
#define TCSETXF		0x5434
#define TCSETXW		0x5435
#define TIOCVHANGUP	0x5437
#define FIONCLEX	0x5450
#define FIOCLEX		0x5451
#define FIOASYNC	0x5452
#define TIOCSERCONFIG	0x5453
#define TIOCSERGWILD	0x5454
#define TIOCSERSWILD	0x5455
#define TIOCGLCKTRMIOS	0x5456
#define TIOCSLCKTRMIOS	0x5457
#define TIOCSERGSTRUCT	0x5458
#define TIOCSERGETLSR   0x5459
#define TIOCSERGETMULTI 0x545A
#define TIOCSERSETMULTI 0x545B
#define TIOCMIWAIT	0x545C
#define TIOCGICOUNT	0x545D
#define TIOCSER_TEMT	0x01

/* ============================================================================
 * SIGNAL CONSTANTS - from Linux UAPI asm-generic/signal.h
 * ============================================================================
 */

#define _NSIG		64
#define SIGHUP		 1
#define SIGINT		 2
#define SIGQUIT		 3
#define SIGILL		 4
#define SIGTRAP		 5
#define SIGABRT		 6
#define SIGIOT		 6
#define SIGBUS		 7
#define SIGFPE		 8
#define SIGKILL		 9
#define SIGUSR1		10
#define SIGSEGV		11
#define SIGUSR2		12
#define SIGPIPE		13
#define SIGALRM		14
#define SIGTERM		15
#define SIGSTKFLT	16
#define SIGCHLD		17
#define SIGCONT		18
#define SIGSTOP		19
#define SIGTSTP		20
#define SIGTTIN		21
#define SIGTTOU		22
#define SIGURG		23
#define SIGXCPU		24
#define SIGXFSZ		25
#define SIGVTALRM	26
#define SIGPROF		27
#define SIGWINCH	28
#define SIGIO		29
#define SIGLOST		29
#define SIGPWR		30
#define SIGSYS		31
#define	SIGUNUSED	31
#define SIGRTMIN	32
#define SIGSTKSZ	8192

/* ============================================================================
 * SIGNAL MASK OPERATIONS - from Linux UAPI asm-generic/signal-defs.h
 * ============================================================================
 */

#define SIG_BLOCK          0	/* for blocking signals */
#define SIG_UNBLOCK        1	/* for unblocking signals */
#define SIG_SETMASK        2	/* for setting the signal mask */

/* ============================================================================
 * POLL CONSTANTS - from Linux UAPI asm-generic/poll.h
 * ============================================================================
 */

#define POLLIN		0x0001
#define POLLPRI		0x0002
#define POLLOUT		0x0004
#define POLLERR		0x0008
#define POLLHUP		0x0010
#define POLLNVAL	0x0020
#define POLLRDNORM	0x0040
#define POLLRDBAND	0x0080
#define POLLWRNORM	0x0100
#define POLLWRBAND	0x0200
#define POLLMSG		0x0400
#define POLLREMOVE	0x1000
#define POLLRDHUP       0x2000

/* ============================================================================
 * EPOLL CONSTANTS - from Linux UAPI linux/eventpoll.h
 * ============================================================================
 */

#define EPOLL_CTL_ADD 1
#define EPOLL_CTL_DEL 2
#define EPOLL_CTL_MOD 3
#define EPOLL_IOC_TYPE 0x8A

/* ============================================================================
 * CLOCK CONSTANTS - from Linux UAPI linux/time.h
 * ============================================================================
 */

#define CLOCK_REALTIME			0
#define CLOCK_MONOTONIC			1
#define CLOCK_PROCESS_CPUTIME_ID	2
#define CLOCK_THREAD_CPUTIME_ID		3
#define CLOCK_MONOTONIC_RAW		4
#define CLOCK_REALTIME_COARSE		5
#define CLOCK_MONOTONIC_COARSE		6
#define CLOCK_BOOTTIME			7
#define CLOCK_REALTIME_ALARM		8
#define CLOCK_BOOTTIME_ALARM		9
#define CLOCK_SGI_CYCLE			10
#define CLOCK_TAI			11

#endif /* IXLAND_LINUX_ABI_CONSTANTS_H */
