/* IXLandSystem/include/ixland/linux_abi_constants.h
 *
 * AUTO-GENERATED from Linux UAPI headers. DO NOT EDIT BY HAND.
 *
 * This file is generated by scripts/generate_linux_constants.sh
 * from the vendored Linux UAPI headers (third_party/linux-uapi/6.12/arm64/include).
 *
 * PURPOSE:
 * Linux UAPI headers define both constants AND types that conflict with
 * Darwin system headers. This file extracts ONLY constant macro definitions
 * from Linux UAPI so Linux-owner code can use canonical Linux ABI values
 * without bringing in conflicting host types.
 */

#ifndef IXLAND_LINUX_ABI_CONSTANTS_H
#define IXLAND_LINUX_ABI_CONSTANTS_H

#define IX_SIG_BLOCK      0
#define IX_SIG_UNBLOCK    1
#define IX_SIG_SETMASK    2

#define IX_SIGHUP         1
#define IX_SIGINT         2
#define IX_SIGQUIT        3
#define IX_SIGILL         4
#define IX_SIGTRAP        5
#define IX_SIGABRT        6
#define IX_SIGBUS         7
#define IX_SIGFPE         8
#define IX_SIGKILL        9
#define IX_SIGUSR1        10
#define IX_SIGSEGV        11
#define IX_SIGUSR2        12
#define IX_SIGPIPE        13
#define IX_SIGALRM        14
#define IX_SIGTERM        15
#define IX_SIGSTKFLT      16
#define IX_SIGCHLD        17
#define IX_SIGCONT        18
#define IX_SIGSTOP        19
#define IX_SIGTSTP        20
#define IX_SIGTTIN        21
#define IX_SIGTTOU        22
#define IX_SIGURG         23
#define IX_SIGXCPU        24
#define IX_SIGXFSZ        25
#define IX_SIGVTALRM      26
#define IX_SIGPROF        27
#define IX_SIGWINCH       28
#define IX_SIGIO          29
#define IX_SIGPWR         30
#define IX_SIGSYS         31

#endif
